/** 未設定試算表或載入失敗時的示範題庫（翰林二上 · 我的相簿） */
export const DEMO_ZH_ITEMS = [
  {
    lesson: "我的相簿",
    type: "生字",
    word: "厚厚",
    zhuyin: "ㄏㄡˋ ㄏㄡˋ",
    sentence: "這本【厚厚】的剪貼簿，每一頁",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "剪",
    zhuyin: "ㄐㄧㄢˇ",
    sentence: "這本厚厚的【剪】貼簿，每一頁",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "簿",
    zhuyin: "ㄅㄨˋ",
    sentence: "這本厚厚的剪貼【簿】，每一頁",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "頁",
    zhuyin: "ㄧㄝˋ",
    sentence: "這本厚厚的剪貼簿，每一【頁】",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "收集",
    zhuyin: "ㄕㄡ ㄐㄧˊ",
    sentence: "【收集】了很多小鴨子的相片。",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "鴨",
    zhuyin: "ㄧㄚ",
    sentence: "收集了很多小【鴨】子的相片。",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "相",
    zhuyin: "ㄒㄧㄤˋ",
    sentence: "收集了很多小鴨子的【相】片。",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "包",
    zhuyin: "ㄅㄠ",
    sentence: "【包】著尿布的小妹妹，活潑又好奇地看著四周。",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "尿布",
    zhuyin: "ㄋㄧㄠˋ ㄅㄨˋ",
    sentence: "包著【尿布】的小妹妹，活潑又好奇地看著四周。",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "活",
    zhuyin: "ㄏㄨㄛˊ",
    sentence: "包著尿布的小妹妹，【活】潑又好奇地看著四周。",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "演",
    zhuyin: "ㄧㄢˇ",
    sentence: "他在【演】講時，屋子突然搖晃起來。",
  },
  {
    lesson: "我的相簿",
    type: "生字",
    word: "搖晃",
    zhuyin: "ㄧㄠˊ ㄏㄨㄤˋ",
    sentence: "他在演講時，屋子突然【搖晃】起來，原來是地震了。",
  },
];
