/** 自編資優練習題（非市府考卷）。lv 1＝小一升小二可做，lv 2＝含較難。 */
export const GIFTED_BANK = [
  { id: "f001", cat: "fig", lv: 1, q: "哪一個跟其他三個不同類？", options: ["▲▲▲", "●●●", "■■■", "▲▲●"], answer: 3, explain: "前三個都是三個相同圖形。" },
  { id: "f002", cat: "fig", lv: 1, q: "哪一個跟其他三個不同類？", options: ["○△", "□△", "○□", "△△"], answer: 3, explain: "前三個都是兩種不同圖形。" },
  { id: "f003", cat: "fig", lv: 1, q: "哪一個跟其他三個不同類？", options: ["↑↓", "←→", "↖↘", "↑↑"], answer: 3, explain: "前三個方向相反成對。" },
  { id: "f004", cat: "fig", lv: 1, q: "找出下一個：▲ ● ▲ ● ▲ ？", options: ["▲", "●", "■", "◆"], answer: 1, explain: "三角形和圓形輪流出現。" },
  { id: "f005", cat: "fig", lv: 1, q: "找出下一個：■ ■ ● ■ ■ ● ■ ■ ？", options: ["■", "●", "▲", "○"], answer: 1, explain: "兩個正方形後接一個圓。" },
  { id: "f006", cat: "fig", lv: 1, q: "找出下一個：○ ○○ ○○○ ？", options: ["○○○○", "○", "○○", "○○○○○"], answer: 0, explain: "圓的個數每次多 1。" },
  { id: "f007", cat: "fig", lv: 1, q: "找出下一個：▲▲ ●●■ ▲▲ ●●■ ▲▲ ？", options: ["●●■", "▲▲", "■■", "●"], answer: 0, explain: "兩組圖形輪流重複。" },
  { id: "f008", cat: "fig", lv: 1, q: "▲ 對應 △，■ 對應？", options: ["□", "●", "▲", "◆"], answer: 0, explain: "實心對空心。" },
  { id: "f009", cat: "fig", lv: 1, q: "●○ 對應 ○●，■□ 對應？", options: ["□■", "■■", "□□", "■○"], answer: 0, explain: "左右對調。" },
  { id: "f010", cat: "fig", lv: 1, q: "▲● 對應 ▲▲●●，■○ 對應？", options: ["■■○○", "■○", "■■■", "○■"], answer: 0, explain: "每個圖形變成兩個。" },
  { id: "f011", cat: "fig", lv: 1, q: "大▲ 對應 小▲，大● 對應？", options: ["小●", "大■", "小▲", "大●"], answer: 0, explain: "只變大小、形狀不變。" },
  { id: "f012", cat: "fig", lv: 1, q: "↑ 對應 →，→ 對應？", options: ["↓", "←", "↑", "↗"], answer: 0, explain: "順時針轉 90 度。" },
  { id: "f013", cat: "fig", lv: 2, q: "開口朝左的弧 ⊂，順時針轉 90 度後，開口朝哪裡？", options: ["朝下 ∪", "朝右 ⊃", "朝上 ∩", "還是朝左 ⊂"], answer: 0, explain: "順時針：朝左→朝下。" },
  { id: "f014", cat: "fig", lv: 1, q: "左右翻轉：⊂ 會變成？", options: ["⊃", "∪", "∩", "⊂"], answer: 0, explain: "開口改向右。" },
  { id: "f015", cat: "fig", lv: 1, q: "上下翻轉：△ 尖朝上，翻轉後？", options: ["▽", "◁", "▷", "△"], answer: 0, explain: "尖端朝下。" },
  { id: "f016", cat: "fig", lv: 2, q: "哪一個不能由字母 L 旋轉得到？", options: ["＋", "⌐", "¬", "L"], answer: 0, explain: "加號多了一劃，不是 L 轉出來的。" },
  { id: "f017", cat: "fig", lv: 2, q: "一張紙對摺成兩層，在其中一層剪一個小洞（沒剪到摺線）。打開後通常會看到幾個洞？", options: ["1", "2", "3", "4"], answer: 1, explain: "兩層各一個洞，打開後是 2 個。" },
  { id: "f018", cat: "fig", lv: 2, q: "正方形紙對摺一次成三角形，再對摺一次。打開後摺痕最像？", options: ["兩條交叉", "一條直線", "沒有摺痕", "三條平行線"], answer: 0, explain: "兩次對摺常留下交叉摺痕。" },
  { id: "f019", cat: "fig", lv: 1, q: "數一數：底層 3 顆、中層 2 顆、頂層 1 顆疊成塔，一共幾顆？", options: ["5", "6", "7", "9"], answer: 1, explain: "3+2+1=6。" },
  { id: "f020", cat: "fig", lv: 1, q: "兩層積木，每層都是 2×2，一共幾塊？", options: ["4", "6", "8", "10"], answer: 2, explain: "2×2×2＝8。" },
  { id: "f021", cat: "fig", lv: 1, q: "缺了哪一塊：▲●■  ▲●？  選出問號。", options: ["■", "▲", "●", "◆"], answer: 0, explain: "每組都是三角、圓、方。" },
  { id: "f022", cat: "fig", lv: 1, q: "缺了哪一塊：○□○ □○□ ○□？", options: ["○", "□", "△", "■"], answer: 0, explain: "圓與方交替，第三組應接圓。" },
  { id: "f023", cat: "fig", lv: 2, q: "三格從左到右。第一張：黑白白。第二張：白黑白。黑點每次往右一格，第三張最後一格是？", options: ["黑", "白", "灰", "空"], answer: 0, explain: "第三張是白白黑，最後一格是黑。" },
  { id: "f024", cat: "fig", lv: 1, q: "點在圓內 對應 點在圓外。正方形在大圓內 對應？", options: ["正方形在大圓外", "圓在正方形內", "兩個圓", "空白"], answer: 0, explain: "裡外對調。" },
  { id: "f025", cat: "fig", lv: 2, q: "哪一個無法由「一長一短兩段」組成 L？", options: ["L", "Γ", "V", "⌐"], answer: 2, explain: "V 是兩斜邊，不是直角 L。" },
  { id: "f026", cat: "fig", lv: 1, q: "影子在右邊，光源在？", options: ["左邊", "右邊", "上邊", "下邊"], answer: 0, explain: "光源與影子相對。" },
  { id: "f027", cat: "fig", lv: 1, q: "時鐘時針指向 3、分針指向 12，兩針夾角最接近？", options: ["90度", "180度", "45度", "0度"], answer: 0, explain: "3 點是直角。" },
  { id: "f028", cat: "fig", lv: 1, q: "一張長方形紙，沿著比較長的邊對折一次。對折後的紙是什麼形狀？", options: ["比較小的長方形", "三角形", "圓", "比原來更大的長方形"], answer: 0, explain: "對折後還是長方形，只是比較小。" },
  { id: "f029", cat: "fig", lv: 2, q: "正三角形可以切成幾個一樣的小正三角形？（沿三邊中點連線）", options: ["2", "3", "4", "6"], answer: 2, explain: "連中點會切成 4 個。" },
  { id: "f030", cat: "fig", lv: 1, q: "哪一個對稱：左右對摺會完全重疊？", options: ["○", "L", "P", "F"], answer: 0, explain: "圓左右對稱。" },
  { id: "f031", cat: "fig", lv: 2, q: "九宮格中心是 ★，四周是 ○，下一張若 ★ 移到右格，右格原來的 ○ 會到？", options: ["中心", "左邊", "上邊", "消失"], answer: 0, explain: "互相換位。" },
  { id: "f032", cat: "fig", lv: 2, q: "▲ 在 ■ 的上面。把整組右轉 90 度後，▲ 在 ■ 的？", options: ["右邊", "左邊", "上面", "下面"], answer: 0, explain: "順時針後上方跑到右方。" },
  { id: "f033", cat: "fig", lv: 2, q: "三個圓排一排。第一張只塗黑中間，第二張只塗黑右邊。黑點依中→右→左循環，第三張只塗黑？", options: ["左邊", "中間", "三個都黑", "都不黑"], answer: 0, explain: "下一個輪到左邊。" },
  { id: "f034", cat: "fig", lv: 1, q: "線段數：△ 有 3 邊、□ 有 4 邊、五邊形有？", options: ["5", "6", "4", "8"], answer: 0, explain: "五邊形五條邊。" },
  { id: "f035", cat: "fig", lv: 1, q: "少了哪一個：紅▲ 藍● 紅● 藍？", options: ["▲", "●", "■", "○"], answer: 0, explain: "顏色與形狀交叉配對，缺藍▲。" },
  { id: "f036", cat: "fig", lv: 1, q: "重疊：○ 和 ＋ 重疊最像？", options: ["⊕", "◎", "△", "＝"], answer: 0, explain: "圓加十字。" },
  { id: "f037", cat: "fig", lv: 1, q: "哪一個是封閉圖形？", options: ["○", "C", "U", "L"], answer: 0, explain: "圓是封閉的。" },
  { id: "f038", cat: "fig", lv: 1, q: "從上看正方體，看到的是？", options: ["正方形", "長方形", "圓", "三角形"], answer: 0, explain: "正方體各面都是正方形。" },
  { id: "f039", cat: "fig", lv: 2, q: "鏡子在右邊，b 的鏡像最接近？", options: ["d", "p", "q", "b"], answer: 0, explain: "左右鏡射 b 變 d。" },
  { id: "f040", cat: "fig", lv: 1, q: "圖形系列：1 個點、2 個點、4 個點、？", options: ["8 個點", "5 個點", "6 個點", "3 個點"], answer: 0, explain: "每次乘 2。" },
  { id: "f041", cat: "fig", lv: 2, q: "哪一個面積最大？（邊長都用小方格）邊長 3 的正方形 vs 邊長 4 的正方形。", options: ["邊長 4 的正方形", "一樣大", "邊長 3 的", "無法比"], answer: 0, explain: "16 大於 9。" },
  { id: "f042", cat: "fig", lv: 1, q: "剪下大圓的四分之一，剩下最像？", options: ["四分之三圓", "半圓", "小圓", "三角形"], answer: 0, explain: "還剩 3/4。" },
  { id: "f043", cat: "fig", lv: 2, q: "只能往右或往上走。從左下走到右上，要走 2 步右和 2 步上。有幾種走法？", options: ["2", "4", "6", "8"], answer: 2, explain: "四步裡選兩步當「右」，共 6 種。" },
  { id: "f044", cat: "fig", lv: 2, q: "正三角形的三條邊，能不能一筆畫完（筆不離開紙、每條邊只畫一次）？", options: ["可以", "不可以", "不一定", "只能畫兩條"], answer: 0, explain: "三邊相連，可以一筆畫完。" },
  { id: "f045", cat: "fig", lv: 1, q: "俯視 2×2 都有積木，其中一格堆 3 塊、其餘各 1 塊，一共？", options: ["6", "5", "7", "8"], answer: 0, explain: "3+1+1+1＝6。" },
  { id: "f046", cat: "fig", lv: 1, q: "圖形類比：小中大 對應 淡中濃，慢中快 對應？", options: ["少中多", "快中慢", "上中下", "左中右"], answer: 0, explain: "程度由弱到強。" },
  { id: "f047", cat: "fig", lv: 2, q: "點線：兩點決定一條直線。三點不共線最多幾條直線？", options: ["3", "1", "2", "4"], answer: 0, explain: "兩兩連線 3 條。" },
  { id: "f048", cat: "fig", lv: 2, q: "四個正方形排成一長條。這樣的展開圖能不能折成正方體？", options: ["不能", "能", "不一定", "只能折成長方體"], answer: 0, explain: "一列四格包不住正方體。" },
  { id: "f049", cat: "fig", lv: 2, q: "對稱軸：長方形（長大於寬）有幾條對稱軸？", options: ["2", "1", "4", "0"], answer: 0, explain: "橫、直各一，沒有對角線。" },
  { id: "f050", cat: "fig", lv: 1, q: "下一個角度：90°、180°、270°、？", options: ["360°", "0°", "200°", "300°"], answer: 0, explain: "每次加 90°。" },
  { id: "f051", cat: "fig", lv: 2, q: "外面和裡面對調：外圓內三角 對應 外三角內圓。那麼 外方內圓 對應？", options: ["外圓內方", "外方內方", "外三角內圓", "外圓內圓"], answer: 0, explain: "外、內對調。" },
  { id: "l052", cat: "lang", lv: 1, q: "「熱」的相反是？", options: ["冷", "溫", "火", "快"], answer: 0, explain: "反義。" },
  { id: "l053", cat: "lang", lv: 1, q: "「快」的相反是？", options: ["慢", "急", "速", "奔"], answer: 0, explain: "反義。" },
  { id: "l054", cat: "lang", lv: 1, q: "「高」的相反是？", options: ["低", "長", "遠", "大"], answer: 0, explain: "反義。" },
  { id: "l055", cat: "lang", lv: 1, q: "「開」的相反是？", options: ["關", "門", "走", "放"], answer: 0, explain: "反義。" },
  { id: "l056", cat: "lang", lv: 1, q: "「安全」的相反是？", options: ["危險", "平安", "保護", "小心"], answer: 0, explain: "反義。" },
  { id: "l057", cat: "lang", lv: 1, q: "「開始」的相反是？", options: ["結束", "繼續", "出發", "起點"], answer: 0, explain: "反義。" },
  { id: "l058", cat: "lang", lv: 1, q: "「誠實」的相反是？", options: ["欺騙", "坦白", "認真", "客氣"], answer: 0, explain: "反義。" },
  { id: "l059", cat: "lang", lv: 1, q: "鳥：天空＝魚：？", options: ["水裡", "樹上", "路上", "雲上"], answer: 0, explain: "生活環境。" },
  { id: "l060", cat: "lang", lv: 1, q: "眼睛：看＝耳朵：？", options: ["聽", "說", "走", "吃"], answer: 0, explain: "器官與功能。" },
  { id: "l061", cat: "lang", lv: 1, q: "筆：寫＝刀：？", options: ["切", "看", "跑", "喝"], answer: 0, explain: "工具與用途。" },
  { id: "l062", cat: "lang", lv: 1, q: "老師：學校＝醫生：？", options: ["醫院", "商店", "車站", "公園"], answer: 0, explain: "職業與場所。" },
  { id: "l063", cat: "lang", lv: 1, q: "白天：太陽＝夜晚：？", options: ["月亮", "星星", "燈塔", "早餐"], answer: 0, explain: "時段與常見天體。" },
  { id: "l064", cat: "lang", lv: 1, q: "手套：手＝鞋子：？", options: ["腳", "頭", "衣服", "襪子"], answer: 0, explain: "穿戴位置。" },
  { id: "l065", cat: "lang", lv: 1, q: "書：讀＝歌：？", options: ["唱", "寫", "跑", "睡"], answer: 0, explain: "對象與動作。" },
  { id: "l066", cat: "lang", lv: 1, q: "哪一個跟其他三個不同類？", options: ["蘋果", "香蕉", "葡萄", "青菜"], answer: 3, explain: "前三是水果。" },
  { id: "l067", cat: "lang", lv: 1, q: "哪一個跟其他三個不同類？", options: ["貓", "狗", "兔", "桌子"], answer: 3, explain: "前三是動物。" },
  { id: "l068", cat: "lang", lv: 1, q: "哪一個跟其他三個不同類？", options: ["紅", "藍", "綠", "圓"], answer: 3, explain: "前三是顏色。" },
  { id: "l069", cat: "lang", lv: 1, q: "哪一個跟其他三個不同類？", options: ["跑", "跳", "走", "椅子"], answer: 3, explain: "前三是動作。" },
  { id: "l070", cat: "lang", lv: 1, q: "哪一個跟其他三個不同類？", options: ["星期一", "星期二", "星期三", "春天"], answer: 3, explain: "前三是星期。" },
  { id: "l071", cat: "lang", lv: 1, q: "量詞：一（　）書", options: ["本", "張", "條", "顆"], answer: 0, explain: "書用「本」。" },
  { id: "l072", cat: "lang", lv: 1, q: "量詞：一（　）樹", options: ["棵", "隻", "朵", "面"], answer: 0, explain: "樹用「棵」。" },
  { id: "l073", cat: "lang", lv: 1, q: "量詞：一（　）魚", options: ["條", "本", "間", "頂"], answer: 0, explain: "魚常用「條」。" },
  { id: "l074", cat: "lang", lv: 1, q: "量詞：一（　）花", options: ["朵", "雙", "輛", "封"], answer: 0, explain: "花用「朵」。" },
  { id: "l075", cat: "lang", lv: 1, q: "把句子排好：①去公園 ②小美 ③下午", options: ["②③①", "①②③", "③①②", "②①③"], answer: 0, explain: "小美下午去公園。" },
  { id: "l076", cat: "lang", lv: 1, q: "把兩句排成通順的因果：①所以遲到了 ②他起床晚了", options: ["②①", "①②", "只留①", "只留②"], answer: 0, explain: "先說原因再結果。" },
  { id: "l077", cat: "lang", lv: 2, q: "「一石二鳥」比較接近？", options: ["做一件事得到兩種好處", "石頭打兩隻鳥才對", "不能同時做兩件事", "要很用力"], answer: 0, explain: "成語比喻。" },
  { id: "l078", cat: "lang", lv: 2, q: "「畫蛇添足」比較接近？", options: ["多做了多餘的事", "蛇本來就有腳", "畫畫一定要添顏色", "要仔細觀察"], answer: 0, explain: "多餘反而壞事。" },
  { id: "l079", cat: "lang", lv: 2, q: "「守株待兔」比較接近？", options: ["只想靠運氣、不努力", "種樹等兔子", "兔子都很快", "守門很重要"], answer: 0, explain: "成語比喻。" },
  { id: "l080", cat: "lang", lv: 1, q: "短文：妹妹把杯子打破了，她立刻跟媽媽說對不起。妹妹的表現是？", options: ["誠實面對", "逃走", "責怪杯子", "假裝沒看到"], answer: 0, explain: "主動認錯。" },
  { id: "l081", cat: "lang", lv: 1, q: "短文：下雨了，阿明沒帶傘。他最可能怎麼做？", options: ["在屋簷下等雨小或借傘", "在操場跑步", "把書放外面淋雨", "脫衣服去游泳"], answer: 0, explain: "生活推理。" },
  { id: "l082", cat: "lang", lv: 1, q: "「因為肚子餓，所以……」接著最合理的是？", options: ["去吃飯", "去睡覺不吃", "把燈打開就飽", "把書包合起來"], answer: 0, explain: "因果。" },
  { id: "l083", cat: "lang", lv: 1, q: "哪一句意思最完整？", options: ["小鳥在樹上唱歌。", "小鳥。", "在樹上。", "唱歌。"], answer: 0, explain: "有主語和完整事件。" },
  { id: "l084", cat: "lang", lv: 1, q: "「他高興得跳起來。」這句寫的是？", options: ["心情很好", "他很生氣", "他受傷了", "他想睡覺"], answer: 0, explain: "高興。" },
  { id: "l085", cat: "lang", lv: 2, q: "「書包」的第一個字是？", options: ["書", "樹", "輸", "舒"], answer: 0, explain: "書包的書。" },
  { id: "l086", cat: "lang", lv: 2, q: "「坐」和「座」：公車上一（　）", options: ["座", "坐", "做", "作"], answer: 0, explain: "量詞用座。" },
  { id: "l087", cat: "lang", lv: 2, q: "「在」和「再」：請（　）說一次", options: ["再", "在", "怎", "只"], answer: 0, explain: "再＝又一次。" },
  { id: "l088", cat: "lang", lv: 1, q: "同類：桌、椅、櫃都是？", options: ["家具", "食物", "天氣", "顏色"], answer: 0, explain: "歸納。" },
  { id: "l089", cat: "lang", lv: 1, q: "「春天」比較不會想到？", options: ["下雪封路整季", "花開", "暖和", "新芽"], answer: 0, explain: "春天不主打嚴寒大雪。" },
  { id: "l090", cat: "lang", lv: 1, q: "聽意思：把「小白兔」的「小」去掉，剩下？", options: ["白兔", "小白", "兔小", "白白"], answer: 0, explain: "刪字。" },
  { id: "l091", cat: "lang", lv: 2, q: "黑對白，明對？", options: ["暗", "亮", "燈", "夜"], answer: 0, explain: "相對的詞。" },
  { id: "l092", cat: "lang", lv: 1, q: "「專心」最接近？", options: ["把注意力放在一件事", "同時做十件事", "一直說話", "到處走動"], answer: 0, explain: "詞義。" },
  { id: "l093", cat: "lang", lv: 1, q: "哪一句最有禮貌？", options: ["請把鉛筆借我，謝謝。", "把筆給我！", "還不快拿來", "我拿走了喔不管你"], answer: 0, explain: "請、謝謝。" },
  { id: "l094", cat: "lang", lv: 1, q: "故事：種子埋進土裡，過幾天冒出芽。接下來最可能？", options: ["繼續長大開花或長葉", "立刻變成兔子", "飛到月亮", "變成石頭"], answer: 0, explain: "植物生長。" },
  { id: "l095", cat: "lang", lv: 1, q: "「上面」的相反是？", options: ["下面", "裡面", "旁邊", "前面"], answer: 0, explain: "方位反義。" },
  { id: "l096", cat: "lang", lv: 1, q: "「左」的相反是？", options: ["右", "上", "前", "外"], answer: 0, explain: "方位。" },
  { id: "l097", cat: "lang", lv: 1, q: "選出標點最合理：今天天氣真好（　）我們去公園。", options: ["，", "？", "、", "．"], answer: 0, explain: "逗號接後句。" },
  { id: "l098", cat: "lang", lv: 2, q: "「他不但會唱歌，還會跳舞。」強調？", options: ["兩樣都會", "只會唱歌", "不會跳舞", "都不喜歡"], answer: 0, explain: "不但…還…" },
  { id: "l099", cat: "lang", lv: 1, q: "哪一個是問句？", options: ["你吃過飯了嗎？", "我吃過飯了。", "快去吃飯！", "吃飯。"], answer: 0, explain: "有「嗎」和問號。" },
  { id: "l100", cat: "lang", lv: 2, q: "「一本新書」的「新」是在說？", options: ["書的狀態", "書的顏色一定紅", "書會跑", "書是動物"], answer: 0, explain: "形容詞。" },
  { id: "l101", cat: "lang", lv: 1, q: "排列成通順詞：①的 ②紅 ③花", options: ["②①③", "①②③", "③②①", "②③①"], answer: 0, explain: "紅的花。" },
  { id: "l102", cat: "lang", lv: 1, q: "「時間過得真快」比較像在說？", options: ["覺得一下子就過去了", "時鐘壞掉", "今天有 48 小時", "沒有昨天"], answer: 0, explain: "感受。" },
  { id: "l103", cat: "lang", lv: 1, q: "誰最可能說「請排隊」？", options: ["圖書館或商店的工作人員", "森林裡的兔子", "正在睡覺的人", "一隻鉛筆"], answer: 0, explain: "生活情境。" },
  { id: "l104", cat: "lang", lv: 1, q: "「合作」最接近？", options: ["大家一起完成", "一個人搶著做", "誰都不做", "互相吵架"], answer: 0, explain: "詞義。" },
  { id: "l105", cat: "lang", lv: 1, q: "短文：公車來了，奶奶走得慢。小華怎麼做最合適？", options: ["讓奶奶先上、必要時幫忙", "自己衝第一不管她", "把門擋住不讓上", "嘲笑她"], answer: 0, explain: "同理心。" },
  { id: "l106", cat: "lang", lv: 1, q: "「水果」包含下面哪一個？", options: ["西瓜", "桌子", "雲", "鞋子"], answer: 0, explain: "類屬。" },
  { id: "m107", cat: "math", lv: 1, q: "2、4、6、8、？", options: ["10", "9", "12", "7"], answer: 0, explain: "每次加 2。" },
  { id: "m108", cat: "math", lv: 1, q: "3、6、9、12、？", options: ["15", "13", "16", "14"], answer: 0, explain: "每次加 3。" },
  { id: "m109", cat: "math", lv: 2, q: "1、2、4、8、？", options: ["16", "10", "12", "9"], answer: 0, explain: "每次乘 2。" },
  { id: "m110", cat: "math", lv: 2, q: "1、3、6、10、？", options: ["15", "12", "13", "14"], answer: 0, explain: "加 2、3、4、5。" },
  { id: "m111", cat: "math", lv: 2, q: "2、6、12、20、？", options: ["30", "24", "28", "22"], answer: 0, explain: "加 4、6、8、10。" },
  { id: "m112", cat: "math", lv: 1, q: "5、10、20、40、？", options: ["80", "50", "60", "45"], answer: 0, explain: "每次乘 2。" },
  { id: "m113", cat: "math", lv: 1, q: "9、7、5、3、？", options: ["1", "2", "0", "4"], answer: 0, explain: "每次減 2。" },
  { id: "m114", cat: "math", lv: 2, q: "1、4、9、16、？", options: ["25", "20", "18", "24"], answer: 0, explain: "平方：1² 2² 3² 4² 5²。" },
  { id: "m115", cat: "math", lv: 2, q: "2、3、5、8、13、？", options: ["21", "18", "16", "20"], answer: 0, explain: "前兩項相加（費氏）。" },
  { id: "m116", cat: "math", lv: 1, q: "10、20、30、40、？", options: ["50", "45", "60", "35"], answer: 0, explain: "每次加 10。" },
  { id: "m117", cat: "math", lv: 1, q: "100、90、80、70、？", options: ["60", "65", "50", "75"], answer: 0, explain: "每次減 10。" },
  { id: "m118", cat: "math", lv: 1, q: "8、16、24、32、？", options: ["40", "36", "34", "48"], answer: 0, explain: "每次加 8。" },
  { id: "m119", cat: "math", lv: 1, q: "7、14、21、28、？", options: ["35", "30", "32", "42"], answer: 0, explain: "7 的倍數。" },
  { id: "m120", cat: "math", lv: 2, q: "81、27、9、3、？", options: ["1", "0", "6", "2"], answer: 0, explain: "每次除以 3。" },
  { id: "m121", cat: "math", lv: 1, q: "64、32、16、8、？", options: ["4", "6", "2", "10"], answer: 0, explain: "每次除以 2。" },
  { id: "m122", cat: "math", lv: 2, q: "1、1、2、3、5、？", options: ["8", "6", "7", "9"], answer: 0, explain: "費氏數列。" },
  { id: "m123", cat: "math", lv: 1, q: "6、12、18、24、？", options: ["30", "26", "28", "36"], answer: 0, explain: "每次加 6。" },
  { id: "m124", cat: "math", lv: 1, q: "11、22、33、44、？", options: ["55", "50", "46", "66"], answer: 0, explain: "11 的倍數。" },
  { id: "m125", cat: "math", lv: 1, q: "4、8、12、16、？", options: ["20", "18", "24", "14"], answer: 0, explain: "每次加 4。" },
  { id: "m126", cat: "math", lv: 2, q: "2、4、8、14、22、？", options: ["32", "28", "30", "26"], answer: 0, explain: "加 2、4、6、8、10。" },
  { id: "m127", cat: "math", lv: 1, q: "一盒 12 顆糖，3 盒有幾顆？", options: ["36", "15", "24", "30"], answer: 0, explain: "12×3。" },
  { id: "m128", cat: "math", lv: 1, q: "36 人平均分成 4 組，一組幾人？", options: ["9", "8", "6", "12"], answer: 0, explain: "36÷4。" },
  { id: "m129", cat: "math", lv: 1, q: "小華有 48 元，買 3 枝筆，一枝 9 元，剩下？", options: ["21", "27", "15", "39"], answer: 0, explain: "48-27=21。" },
  { id: "m130", cat: "math", lv: 2, q: "長方形長 8、寬 5，周長是？", options: ["26", "40", "13", "20"], answer: 0, explain: "（8+5）×2=26。" },
  { id: "m131", cat: "math", lv: 1, q: "正方形邊長 6，周長是？", options: ["24", "36", "12", "18"], answer: 0, explain: "6×4。" },
  { id: "m132", cat: "math", lv: 1, q: "現在 3 點，再過 2 小時是？", options: ["5 點", "4 點", "6 點", "1 點"], answer: 0, explain: "3+2。" },
  { id: "m133", cat: "math", lv: 1, q: "一小時有 60 分鐘。2 小時有幾分鐘？", options: ["120", "80", "100", "62"], answer: 0, explain: "60×2。" },
  { id: "m134", cat: "math", lv: 2, q: "7 個人每兩人握一次手，共握幾次？（每對一次）", options: ["21", "14", "7", "49"], answer: 0, explain: "C(7,2)=21。" },
  { id: "m135", cat: "math", lv: 2, q: "從 1 加到 10 等於？", options: ["55", "45", "50", "65"], answer: 0, explain: "10×11/2。" },
  { id: "m136", cat: "math", lv: 1, q: "一個數加上 8 等於 20，這個數是？", options: ["12", "28", "8", "10"], answer: 0, explain: "20-8。" },
  { id: "m137", cat: "math", lv: 1, q: "□ × 6 ＝ 42，□ 是？", options: ["7", "6", "8", "5"], answer: 0, explain: "42÷6。" },
  { id: "m138", cat: "math", lv: 1, q: "比 100 少 25 是？", options: ["75", "125", "80", "85"], answer: 0, explain: "100-25。" },
  { id: "m139", cat: "math", lv: 1, q: "3 個 15 是多少？", options: ["45", "18", "35", "53"], answer: 0, explain: "15×3。" },
  { id: "m140", cat: "math", lv: 1, q: "雞 2 隻腳、兔子 4 隻腳。2 雞 3 兔共幾隻腳？", options: ["16", "14", "12", "20"], answer: 0, explain: "4+12=16。" },
  { id: "m141", cat: "math", lv: 2, q: "路長 10 公尺，每隔 2 公尺種一棵（含兩端），種幾棵？", options: ["6", "5", "4", "10"], answer: 0, explain: "10/2+1=6。" },
  { id: "m142", cat: "math", lv: 1, q: "一排座位 8 個，已坐 3 人，還空？", options: ["5", "11", "8", "3"], answer: 0, explain: "8-3。" },
  { id: "m143", cat: "math", lv: 1, q: "糖果 25 顆，給弟弟 8 顆、妹妹 7 顆，自己剩？", options: ["10", "15", "9", "12"], answer: 0, explain: "25-8-7。" },
  { id: "m144", cat: "math", lv: 1, q: "9 的 4 倍是？", options: ["36", "13", "32", "45"], answer: 0, explain: "9×4。" },
  { id: "m145", cat: "math", lv: 1, q: "一半的 16 是？", options: ["8", "32", "4", "12"], answer: 0, explain: "16÷2。" },
  { id: "m146", cat: "math", lv: 2, q: "先算出來再比：哪個最大？", options: ["5×5", "3×8", "2×12", "4×6"], answer: 0, explain: "25 最大，另外三個都是 24。" },
  { id: "m147", cat: "math", lv: 2, q: "2＋3×4 等於？（先乘後加）", options: ["14", "20", "24", "11"], answer: 0, explain: "2+12=14。" },
  { id: "m148", cat: "math", lv: 1, q: "缺數：5、10、15、□、25", options: ["20", "16", "18", "22"], answer: 0, explain: "每次加 5。" },
  { id: "m149", cat: "math", lv: 1, q: "一個披萨切成 8 片，吃了 3 片，剩幾片？", options: ["5", "11", "8", "3"], answer: 0, explain: "8-3。" },
  { id: "m150", cat: "math", lv: 1, q: "3 個小朋友平分 18 顆糖，每人幾顆？", options: ["6", "15", "21", "9"], answer: 0, explain: "18÷3。" },
  { id: "m151", cat: "math", lv: 1, q: "最重的是？ 1 公斤棉花 和 1 公斤鐵", options: ["一樣重", "鐵", "棉花", "看體積"], answer: 0, explain: "都是 1 公斤。" },
  { id: "m152", cat: "math", lv: 2, q: "一杯水平均倒進 3 個空小杯，每小杯是原來的多少？", options: ["三分之一杯", "一杯", "三杯", "半杯"], answer: 0, explain: "1÷3。" },
  { id: "m153", cat: "math", lv: 2, q: "班級 28 人，男生比女生多 4 人。女生幾人？", options: ["12", "16", "14", "10"], answer: 0, explain: "女 x、男 x+4，2x+4=28，x=12。" },
  { id: "m154", cat: "math", lv: 1, q: "買 2 盒，每盒 4 排，每排 5 枝，共幾枝鉛筆？", options: ["40", "20", "10", "45"], answer: 0, explain: "2×4×5。" },
  { id: "m155", cat: "math", lv: 2, q: "用數字 8、8、3 排出一個三位數，最大是？", options: ["883", "838", "388", "833"], answer: 0, explain: "百位、十位先放大的 8。" },
  { id: "m156", cat: "math", lv: 1, q: "今天星期二，再過 8 天是星期幾？", options: ["三", "一", "四", "日"], answer: 0, explain: "8=7+1，星期二再 1 天是三。" },
  { id: "m157", cat: "math", lv: 1, q: "時針走一圈是 12 小時。從 2 點到 8 點走了幾小時？", options: ["6", "10", "8", "4"], answer: 0, explain: "8-2。" },
  { id: "m158", cat: "math", lv: 1, q: "□＋□＋□＝15，每個□相同，□是？", options: ["5", "3", "15", "6"], answer: 0, explain: "15÷3。" },
  { id: "m159", cat: "math", lv: 1, q: "比 36 多 9 的數，再減 5，得？", options: ["40", "30", "50", "22"], answer: 0, explain: "36+9-5=40。" },
  { id: "m160", cat: "math", lv: 2, q: "4 個連續整數和是 14，最小的是？", options: ["2", "1", "3", "4"], answer: 0, explain: "2+3+4+5=14。" },
  { id: "m161", cat: "math", lv: 1, q: "若 ▲＝3、●＝5，▲＋●＋▲＝？", options: ["11", "8", "15", "35"], answer: 0, explain: "3+5+3。" },
  { id: "m162", cat: "math", lv: 1, q: "圖形對應：△＝2、□□＝8，則 △△△＝？", options: ["6", "24", "5", "16"], answer: 0, explain: "一個三角是 2，三個是 6。" },
];

export const GIFTED_CAT_LABEL = { fig: "圖形", lang: "語文", math: "數學" };
export const GIFTED_LV_LABEL = { 1: "小一升小二可做", 2: "較難" };

