/** 自編魏氏風格推理練習（非官方魏氏／WISC 試題，無 IQ、無 PR）。grade：12＝1～2年、23＝2～3年、34＝3～4年、56＝5～6年。 */
export const GIFTED_BANK = [
  { id: "f001", cat: "fig", grade: 12, q: "哪一個跟其他三個不同類？", options: ["▲▲▲", "●●●", "■■■", "▲▲●"], answer: 3, explain: "前三個都是三個相同圖形。" },
  { id: "f002", cat: "fig", grade: 12, q: "哪一個跟其他三個不同類？", options: ["○△", "□△", "○□", "△△"], answer: 3, explain: "前三個都是兩種不同圖形。" },
  { id: "f003", cat: "fig", grade: 12, q: "哪一個跟其他三個不同類？", options: ["↑↓", "←→", "↖↘", "↑↑"], answer: 3, explain: "前三個方向相反成對。" },
  { id: "f004", cat: "fig", grade: 12, q: "找出下一個：▲ ● ▲ ● ▲ ？", options: ["▲", "●", "■", "◆"], answer: 1, explain: "三角形和圓形輪流出現。" },
  { id: "f005", cat: "fig", grade: 12, q: "找出下一個：■ ■ ● ■ ■ ● ■ ■ ？", options: ["■", "●", "▲", "○"], answer: 1, explain: "兩個正方形後接一個圓。" },
  { id: "f006", cat: "fig", grade: 12, q: "找出下一個：○ ○○ ○○○ ？", options: ["○○○○", "○", "○○", "○○○○○"], answer: 0, explain: "圓的個數每次多 1。" },
  { id: "f007", cat: "fig", grade: 12, q: "找出下一個：▲▲ ●●■ ▲▲ ●●■ ▲▲ ？", options: ["●●■", "▲▲", "■■", "●"], answer: 0, explain: "兩組圖形輪流重複。" },
  { id: "f008", cat: "fig", grade: 12, q: "▲ 對應 △，■ 對應？", options: ["□", "●", "▲", "◆"], answer: 0, explain: "實心對空心。" },
  { id: "f009", cat: "fig", grade: 12, q: "●○ 對應 ○●，■□ 對應？", options: ["□■", "■■", "□□", "■○"], answer: 0, explain: "左右對調。" },
  { id: "f010", cat: "fig", grade: 12, q: "▲● 對應 ▲▲●●，■○ 對應？", options: ["■■○○", "■○", "■■■", "○■"], answer: 0, explain: "每個圖形變成兩個。" },
  { id: "f011", cat: "fig", grade: 12, q: "大▲ 對應 小▲，大● 對應？", options: ["小●", "大■", "小▲", "大●"], answer: 0, explain: "只變大小、形狀不變。" },
  { id: "f012", cat: "fig", grade: 12, q: "↑ 對應 →，→ 對應？", options: ["↓", "←", "↑", "↗"], answer: 0, explain: "順時針轉 90 度。" },
  { id: "f013", cat: "fig", grade: 23, q: "開口朝左的弧 ⊂，順時針轉 90 度後，開口朝哪裡？", options: ["朝下 ∪", "朝右 ⊃", "朝上 ∩", "還是朝左 ⊂"], answer: 0, explain: "順時針：朝左→朝下。" },
  { id: "f014", cat: "fig", grade: 12, q: "左右翻轉：⊂ 會變成？", options: ["⊃", "∪", "∩", "⊂"], answer: 0, explain: "開口改向右。" },
  { id: "f015", cat: "fig", grade: 12, q: "上下翻轉：△ 尖朝上，翻轉後？", options: ["▽", "◁", "▷", "△"], answer: 0, explain: "尖端朝下。" },
  { id: "f016", cat: "fig", grade: 23, q: "哪一個不能由字母 L 旋轉得到？", options: ["＋", "⌐", "¬", "L"], answer: 0, explain: "加號多了一劃，不是 L 轉出來的。" },
  { id: "f017", cat: "fig", grade: 23, q: "一張紙對摺成兩層。只在其中一層剪一個小洞，而且沒剪到摺線。把紙打開後，洞有幾個？", options: ["1", "2", "3", "4"], answer: 1, explain: "兩層各一個洞，打開後是 2 個。" },
  { id: "f018", cat: "fig", grade: 23, q: "正方形紙先對摺成三角形，再對摺一次。全部打開後，摺痕最接近哪一種？", options: ["兩條交叉", "一條直線", "沒有摺痕", "三條平行線"], answer: 0, explain: "兩次對摺常留下交叉的摺痕。" },
  { id: "f019", cat: "fig", grade: 12, q: "數一數：底層 3 顆、中層 2 顆、頂層 1 顆疊成塔，一共幾顆？", options: ["5", "6", "7", "9"], answer: 1, explain: "3+2+1=6。" },
  { id: "f020", cat: "fig", grade: 12, q: "兩層積木，每層都是 2×2，一共幾塊？", options: ["4", "6", "8", "10"], answer: 2, explain: "2×2×2＝8。" },
  { id: "f021", cat: "fig", grade: 12, q: "缺了哪一塊：▲●■  ▲●？  選出問號。", options: ["■", "▲", "●", "◆"], answer: 0, explain: "每組都是三角、圓、方。" },
  { id: "f022", cat: "fig", grade: 12, q: "缺了哪一塊：○□○ □○□ ○□？", options: ["○", "□", "△", "■"], answer: 0, explain: "圓與方交替，第三組應接圓。" },
  { id: "f023", cat: "fig", grade: 23, q: "三格從左到右。第一張：黑白白。第二張：白黑白。黑點每次往右一格，第三張最後一格是？", options: ["黑", "白", "灰", "空"], answer: 0, explain: "第三張是白白黑，最後一格是黑。" },
  { id: "f024", cat: "fig", grade: 12, q: "點在圓內 對應 點在圓外。正方形在大圓內 對應？", options: ["正方形在大圓外", "圓在正方形內", "兩個圓", "空白"], answer: 0, explain: "裡外對調。" },
  { id: "f025", cat: "fig", grade: 23, q: "哪一個無法由「一長一短兩段」組成 L？", options: ["L", "Γ", "V", "⌐"], answer: 2, explain: "V 是兩斜邊，不是直角 L。" },
  { id: "f026", cat: "fig", grade: 12, q: "影子在右邊，光源在？", options: ["左邊", "右邊", "上邊", "下邊"], answer: 0, explain: "光源與影子相對。" },
  { id: "f027", cat: "fig", grade: 12, q: "時鐘時針指向 3、分針指向 12，兩針夾角最接近？", options: ["90度", "180度", "45度", "0度"], answer: 0, explain: "3 點是直角。" },
  { id: "f028", cat: "fig", grade: 12, q: "一張長方形紙，沿著比較長的邊對折一次。對折後的紙是什麼形狀？", options: ["比較小的長方形", "三角形", "圓", "比原來更大的長方形"], answer: 0, explain: "對折後還是長方形，只是比較小。" },
  { id: "f029", cat: "fig", grade: 23, q: "正三角形可以切成幾個一樣的小正三角形？（沿三邊中點連線）", options: ["2", "3", "4", "6"], answer: 2, explain: "連中點會切成 4 個。" },
  { id: "f030", cat: "fig", grade: 12, q: "哪一個對稱：左右對摺會完全重疊？", options: ["○", "L", "P", "F"], answer: 0, explain: "圓左右對稱。" },
  { id: "f031", cat: "fig", grade: 23, q: "九宮格中心是 ★，四周是 ○，下一張若 ★ 移到右格，右格原來的 ○ 會到？", options: ["中心", "左邊", "上邊", "消失"], answer: 0, explain: "互相換位。" },
  { id: "f032", cat: "fig", grade: 23, q: "▲ 在 ■ 的上面。把整組右轉 90 度後，▲ 在 ■ 的？", options: ["右邊", "左邊", "上面", "下面"], answer: 0, explain: "順時針後上方跑到右方。" },
  { id: "f033", cat: "fig", grade: 23, q: "三個圓排一排，每次只塗黑一格，順序是：中→右→左→中→…。第一張中、第二張右，第三張塗黑哪一格？", options: ["左邊", "中間", "三個都黑", "都不黑"], answer: 0, explain: "中之後是右，右之後是左。" },
  { id: "f034", cat: "fig", grade: 12, q: "線段數：△ 有 3 邊、□ 有 4 邊、五邊形有？", options: ["5", "6", "4", "8"], answer: 0, explain: "五邊形五條邊。" },
  { id: "f035", cat: "fig", grade: 12, q: "少了哪一個：紅▲ 藍● 紅● 藍？", options: ["▲", "●", "■", "○"], answer: 0, explain: "顏色與形狀交叉配對，缺藍▲。" },
  { id: "f036", cat: "fig", grade: 12, q: "重疊：○ 和 ＋ 重疊最像？", options: ["⊕", "◎", "△", "＝"], answer: 0, explain: "圓加十字。" },
  { id: "f037", cat: "fig", grade: 12, q: "哪一個是封閉圖形？", options: ["○", "C", "U", "L"], answer: 0, explain: "圓是封閉的。" },
  { id: "f038", cat: "fig", grade: 12, q: "從上看正方體，看到的是？", options: ["正方形", "長方形", "圓", "三角形"], answer: 0, explain: "正方體各面都是正方形。" },
  { id: "f039", cat: "fig", grade: 23, q: "鏡子在右邊，b 的鏡像最接近？", options: ["d", "p", "q", "b"], answer: 0, explain: "左右鏡射 b 變 d。" },
  { id: "f040", cat: "fig", grade: 12, q: "圖形系列：1 個點、2 個點、4 個點、？", options: ["8 個點", "5 個點", "6 個點", "3 個點"], answer: 0, explain: "每次乘 2。" },
  { id: "f041", cat: "fig", grade: 23, q: "哪一個面積最大？（邊長都用小方格）邊長 3 的正方形 vs 邊長 4 的正方形。", options: ["邊長 4 的正方形", "一樣大", "邊長 3 的", "無法比"], answer: 0, explain: "16 大於 9。" },
  { id: "f042", cat: "fig", grade: 12, q: "剪下大圓的四分之一，剩下最像？", options: ["四分之三圓", "半圓", "小圓", "三角形"], answer: 0, explain: "還剩 3/4。" },
  { id: "f043", cat: "fig", grade: 23, q: "只能往右或往上走。從左下走到右上，要走 2 步右和 2 步上。有幾種走法？", options: ["2", "4", "6", "8"], answer: 2, explain: "四步裡選兩步當「右」，共 6 種。" },
  { id: "f044", cat: "fig", grade: 23, q: "正三角形的三條邊，能不能一筆畫完（筆不離開紙、每條邊只畫一次）？", options: ["可以", "不可以", "不一定", "只能畫兩條"], answer: 0, explain: "三邊相連，可以一筆畫完。" },
  { id: "f045", cat: "fig", grade: 12, q: "俯視 2×2 都有積木，其中一格堆 3 塊、其餘各 1 塊，一共？", options: ["6", "5", "7", "8"], answer: 0, explain: "3+1+1+1＝6。" },
  { id: "f046", cat: "fig", grade: 12, q: "圖形類比：小中大 對應 淡中濃，慢中快 對應？", options: ["少中多", "快中慢", "上中下", "左中右"], answer: 0, explain: "程度由弱到強。" },
  { id: "f047", cat: "fig", grade: 23, q: "點線：兩點決定一條直線。三點不共線最多幾條直線？", options: ["3", "1", "2", "4"], answer: 0, explain: "兩兩連線 3 條。" },
  { id: "f048", cat: "fig", grade: 23, q: "四個正方形排成一長條。這樣的展開圖能不能折成正方體？", options: ["不能", "能", "不一定", "只能折成長方體"], answer: 0, explain: "一列四格包不住正方體。" },
  { id: "f049", cat: "fig", grade: 23, q: "對稱軸：長方形（長大於寬）有幾條對稱軸？", options: ["2", "1", "4", "0"], answer: 0, explain: "橫、直各一，沒有對角線。" },
  { id: "f050", cat: "fig", grade: 12, q: "下一個角度：90°、180°、270°、？", options: ["360°", "0°", "200°", "300°"], answer: 0, explain: "每次加 90°。" },
  { id: "f051", cat: "fig", grade: 23, q: "外面和裡面對調：外圓內三角 對應 外三角內圓。那麼 外方內圓 對應？", options: ["外圓內方", "外方內方", "外三角內圓", "外圓內圓"], answer: 0, explain: "外、內對調。" },
  { id: "l052", cat: "lang", grade: 12, q: "「熱」的相反是？", options: ["冷", "溫", "火", "快"], answer: 0, explain: "反義。" },
  { id: "l053", cat: "lang", grade: 12, q: "「快」的相反是？", options: ["慢", "急", "速", "奔"], answer: 0, explain: "反義。" },
  { id: "l054", cat: "lang", grade: 12, q: "「高」的相反是？", options: ["低", "長", "遠", "大"], answer: 0, explain: "反義。" },
  { id: "l055", cat: "lang", grade: 12, q: "「開」的相反是？", options: ["關", "門", "走", "放"], answer: 0, explain: "反義。" },
  { id: "l056", cat: "lang", grade: 12, q: "「安全」的相反是？", options: ["危險", "平安", "保護", "小心"], answer: 0, explain: "反義。" },
  { id: "l057", cat: "lang", grade: 12, q: "「開始」的相反是？", options: ["結束", "繼續", "出發", "起點"], answer: 0, explain: "反義。" },
  { id: "l058", cat: "lang", grade: 12, q: "「誠實」的相反是？", options: ["欺騙", "坦白", "認真", "客氣"], answer: 0, explain: "反義。" },
  { id: "l059", cat: "lang", grade: 12, q: "鳥：天空＝魚：？", options: ["水裡", "樹上", "路上", "雲上"], answer: 0, explain: "生活環境。" },
  { id: "l060", cat: "lang", grade: 12, q: "眼睛：看＝耳朵：？", options: ["聽", "說", "走", "吃"], answer: 0, explain: "器官與功能。" },
  { id: "l061", cat: "lang", grade: 12, q: "筆：寫＝刀：？", options: ["切", "看", "跑", "喝"], answer: 0, explain: "工具與用途。" },
  { id: "l062", cat: "lang", grade: 12, q: "老師：學校＝醫生：？", options: ["醫院", "商店", "車站", "公園"], answer: 0, explain: "職業與場所。" },
  { id: "l063", cat: "lang", grade: 12, q: "白天：太陽＝夜晚：？", options: ["月亮", "星星", "燈塔", "早餐"], answer: 0, explain: "時段與常見天體。" },
  { id: "l064", cat: "lang", grade: 12, q: "手套：手＝鞋子：？", options: ["腳", "頭", "衣服", "襪子"], answer: 0, explain: "穿戴位置。" },
  { id: "l065", cat: "lang", grade: 12, q: "書：讀＝歌：？", options: ["唱", "寫", "跑", "睡"], answer: 0, explain: "對象與動作。" },
  { id: "l066", cat: "lang", grade: 12, q: "哪一個跟其他三個不同類？", options: ["蘋果", "香蕉", "葡萄", "青菜"], answer: 3, explain: "前三是水果。" },
  { id: "l067", cat: "lang", grade: 12, q: "哪一個跟其他三個不同類？", options: ["貓", "狗", "兔", "桌子"], answer: 3, explain: "前三是動物。" },
  { id: "l068", cat: "lang", grade: 12, q: "哪一個跟其他三個不同類？", options: ["紅", "藍", "綠", "圓"], answer: 3, explain: "前三是顏色。" },
  { id: "l069", cat: "lang", grade: 12, q: "哪一個跟其他三個不同類？", options: ["跑", "跳", "走", "椅子"], answer: 3, explain: "前三是動作。" },
  { id: "l070", cat: "lang", grade: 12, q: "哪一個跟其他三個不同類？", options: ["星期一", "星期二", "星期三", "春天"], answer: 3, explain: "前三是星期。" },
  { id: "l071", cat: "lang", grade: 12, q: "量詞：一（　）書", options: ["本", "張", "條", "顆"], answer: 0, explain: "書用「本」。" },
  { id: "l072", cat: "lang", grade: 12, q: "量詞：一（　）樹", options: ["棵", "隻", "朵", "面"], answer: 0, explain: "樹用「棵」。" },
  { id: "l073", cat: "lang", grade: 12, q: "量詞：一（　）魚", options: ["條", "本", "間", "頂"], answer: 0, explain: "魚常用「條」。" },
  { id: "l074", cat: "lang", grade: 12, q: "量詞：一（　）花", options: ["朵", "雙", "輛", "封"], answer: 0, explain: "花用「朵」。" },
  { id: "l075", cat: "lang", grade: 12, q: "把句子排好：①去公園 ②小美 ③下午", options: ["②③①", "①②③", "③①②", "②①③"], answer: 0, explain: "小美下午去公園。" },
  { id: "l076", cat: "lang", grade: 12, q: "把兩句排成通順的因果：①所以遲到了 ②他起床晚了", options: ["②①", "①②", "只留①", "只留②"], answer: 0, explain: "先說原因再結果。" },
  { id: "l077", cat: "lang", grade: 23, q: "「一石二鳥」比較接近？", options: ["做一件事得到兩種好處", "石頭打兩隻鳥才對", "不能同時做兩件事", "要很用力"], answer: 0, explain: "成語比喻。" },
  { id: "l078", cat: "lang", grade: 23, q: "「畫蛇添足」比較接近？", options: ["多做了多餘的事", "蛇本來就有腳", "畫畫一定要添顏色", "要仔細觀察"], answer: 0, explain: "多餘反而壞事。" },
  { id: "l079", cat: "lang", grade: 23, q: "「守株待兔」比較接近？", options: ["只想靠運氣、不努力", "種樹等兔子", "兔子都很快", "守門很重要"], answer: 0, explain: "成語比喻。" },
  { id: "l080", cat: "lang", grade: 12, q: "短文：妹妹把杯子打破了，她立刻跟媽媽說對不起。妹妹的表現是？", options: ["誠實面對", "逃走", "責怪杯子", "假裝沒看到"], answer: 0, explain: "主動認錯。" },
  { id: "l081", cat: "lang", grade: 12, q: "短文：下雨了，阿明沒帶傘。他最可能怎麼做？", options: ["在屋簷下等雨小或借傘", "在操場跑步", "把書放外面淋雨", "脫衣服去游泳"], answer: 0, explain: "生活推理。" },
  { id: "l082", cat: "lang", grade: 12, q: "「因為肚子餓，所以……」接著最合理的是？", options: ["去吃飯", "去睡覺不吃", "把燈打開就飽", "把書包合起來"], answer: 0, explain: "因果。" },
  { id: "l083", cat: "lang", grade: 12, q: "哪一句意思最完整？", options: ["小鳥在樹上唱歌。", "小鳥。", "在樹上。", "唱歌。"], answer: 0, explain: "有主語和完整事件。" },
  { id: "l084", cat: "lang", grade: 12, q: "「他高興得跳起來。」這句寫的是？", options: ["心情很好", "他很生氣", "他受傷了", "他想睡覺"], answer: 0, explain: "高興。" },
  { id: "l085", cat: "lang", grade: 23, q: "「書包」兩個字，第一個字選哪一個？", options: ["書", "樹", "輸", "舒"], answer: 0, explain: "書包的「書」。" },
  { id: "l086", cat: "lang", grade: 23, q: "「坐」和「座」：公車上一（　）", options: ["座", "坐", "做", "作"], answer: 0, explain: "量詞用座。" },
  { id: "l087", cat: "lang", grade: 23, q: "「在」和「再」：請（　）說一次", options: ["再", "在", "怎", "只"], answer: 0, explain: "再＝又一次。" },
  { id: "l088", cat: "lang", grade: 12, q: "同類：桌、椅、櫃都是？", options: ["家具", "食物", "天氣", "顏色"], answer: 0, explain: "歸納。" },
  { id: "l089", cat: "lang", grade: 12, q: "「春天」比較不會想到？", options: ["下雪封路整季", "花開", "暖和", "新芽"], answer: 0, explain: "春天不主打嚴寒大雪。" },
  { id: "l090", cat: "lang", grade: 12, q: "聽意思：把「小白兔」的「小」去掉，剩下？", options: ["白兔", "小白", "兔小", "白白"], answer: 0, explain: "刪字。" },
  { id: "l091", cat: "lang", grade: 23, q: "黑對白，明對？", options: ["暗", "亮", "燈", "夜"], answer: 0, explain: "相對的詞。" },
  { id: "l092", cat: "lang", grade: 12, q: "「專心」最接近？", options: ["把注意力放在一件事", "同時做十件事", "一直說話", "到處走動"], answer: 0, explain: "詞義。" },
  { id: "l093", cat: "lang", grade: 12, q: "哪一句最有禮貌？", options: ["請把鉛筆借我，謝謝。", "把筆給我！", "還不快拿來", "我拿走了喔不管你"], answer: 0, explain: "請、謝謝。" },
  { id: "l094", cat: "lang", grade: 12, q: "故事：種子埋進土裡，過幾天冒出芽。接下來最可能？", options: ["繼續長大開花或長葉", "立刻變成兔子", "飛到月亮", "變成石頭"], answer: 0, explain: "植物生長。" },
  { id: "l095", cat: "lang", grade: 12, q: "「上面」的相反是？", options: ["下面", "裡面", "旁邊", "前面"], answer: 0, explain: "方位反義。" },
  { id: "l096", cat: "lang", grade: 12, q: "「左」的相反是？", options: ["右", "上", "前", "外"], answer: 0, explain: "方位。" },
  { id: "l097", cat: "lang", grade: 12, q: "選出標點最合理：今天天氣真好（　）我們去公園。", options: ["，", "？", "、", "．"], answer: 0, explain: "逗號接後句。" },
  { id: "l098", cat: "lang", grade: 23, q: "「他不但會唱歌，還會跳舞。」強調？", options: ["兩樣都會", "只會唱歌", "不會跳舞", "都不喜歡"], answer: 0, explain: "不但…還…" },
  { id: "l099", cat: "lang", grade: 12, q: "哪一個是問句？", options: ["你吃過飯了嗎？", "我吃過飯了。", "快去吃飯！", "吃飯。"], answer: 0, explain: "有「嗎」和問號。" },
  { id: "l100", cat: "lang", grade: 23, q: "「一本新書」的「新」是在說？", options: ["書的狀態", "書的顏色一定紅", "書會跑", "書是動物"], answer: 0, explain: "形容詞。" },
  { id: "l101", cat: "lang", grade: 12, q: "排列成通順詞：①的 ②紅 ③花", options: ["②①③", "①②③", "③②①", "②③①"], answer: 0, explain: "紅的花。" },
  { id: "l102", cat: "lang", grade: 12, q: "「時間過得真快」比較像在說？", options: ["覺得一下子就過去了", "時鐘壞掉", "今天有 48 小時", "沒有昨天"], answer: 0, explain: "感受。" },
  { id: "l103", cat: "lang", grade: 12, q: "誰最可能說「請排隊」？", options: ["圖書館或商店的工作人員", "森林裡的兔子", "正在睡覺的人", "一隻鉛筆"], answer: 0, explain: "生活情境。" },
  { id: "l104", cat: "lang", grade: 12, q: "「合作」最接近？", options: ["大家一起完成", "一個人搶著做", "誰都不做", "互相吵架"], answer: 0, explain: "詞義。" },
  { id: "l105", cat: "lang", grade: 12, q: "短文：公車來了，奶奶走得慢。小華怎麼做最合適？", options: ["讓奶奶先上、必要時幫忙", "自己衝第一不管她", "把門擋住不讓上", "嘲笑她"], answer: 0, explain: "同理心。" },
  { id: "l106", cat: "lang", grade: 12, q: "「水果」包含下面哪一個？", options: ["西瓜", "桌子", "雲", "鞋子"], answer: 0, explain: "類屬。" },
  { id: "m107", cat: "math", grade: 12, q: "2、4、6、8、？", options: ["10", "9", "12", "7"], answer: 0, explain: "每次加 2。" },
  { id: "m108", cat: "math", grade: 12, q: "3、6、9、12、？", options: ["15", "13", "16", "14"], answer: 0, explain: "每次加 3。" },
  { id: "m109", cat: "math", grade: 23, q: "1、2、4、8、？", options: ["16", "10", "12", "9"], answer: 0, explain: "每次乘 2。" },
  { id: "m110", cat: "math", grade: 23, q: "1、3、6、10、？", options: ["15", "12", "13", "14"], answer: 0, explain: "加 2、3、4、5。" },
  { id: "m111", cat: "math", grade: 23, q: "2、6、12、20、？", options: ["30", "24", "28", "22"], answer: 0, explain: "加 4、6、8、10。" },
  { id: "m112", cat: "math", grade: 12, q: "5、10、20、40、？", options: ["80", "50", "60", "45"], answer: 0, explain: "每次乘 2。" },
  { id: "m113", cat: "math", grade: 12, q: "9、7、5、3、？", options: ["1", "2", "0", "4"], answer: 0, explain: "每次減 2。" },
  { id: "m114", cat: "math", grade: 23, q: "1、4、9、16、？", options: ["25", "20", "18", "24"], answer: 0, explain: "平方：1² 2² 3² 4² 5²。" },
  { id: "m115", cat: "math", grade: 23, q: "2、3、5、8、13、？", options: ["21", "18", "16", "20"], answer: 0, explain: "前兩項相加（費氏）。" },
  { id: "m116", cat: "math", grade: 12, q: "10、20、30、40、？", options: ["50", "45", "60", "35"], answer: 0, explain: "每次加 10。" },
  { id: "m117", cat: "math", grade: 12, q: "100、90、80、70、？", options: ["60", "65", "50", "75"], answer: 0, explain: "每次減 10。" },
  { id: "m118", cat: "math", grade: 12, q: "8、16、24、32、？", options: ["40", "36", "34", "48"], answer: 0, explain: "每次加 8。" },
  { id: "m119", cat: "math", grade: 12, q: "7、14、21、28、？", options: ["35", "30", "32", "42"], answer: 0, explain: "7 的倍數。" },
  { id: "m120", cat: "math", grade: 23, q: "81、27、9、3、？", options: ["1", "0", "6", "2"], answer: 0, explain: "每次除以 3。" },
  { id: "m121", cat: "math", grade: 12, q: "64、32、16、8、？", options: ["4", "6", "2", "10"], answer: 0, explain: "每次除以 2。" },
  { id: "m122", cat: "math", grade: 23, q: "1、1、2、3、5、？", options: ["8", "6", "7", "9"], answer: 0, explain: "費氏數列。" },
  { id: "m123", cat: "math", grade: 12, q: "6、12、18、24、？", options: ["30", "26", "28", "36"], answer: 0, explain: "每次加 6。" },
  { id: "m124", cat: "math", grade: 12, q: "11、22、33、44、？", options: ["55", "50", "46", "66"], answer: 0, explain: "11 的倍數。" },
  { id: "m125", cat: "math", grade: 12, q: "4、8、12、16、？", options: ["20", "18", "24", "14"], answer: 0, explain: "每次加 4。" },
  { id: "m126", cat: "math", grade: 23, q: "2、4、8、14、22、？", options: ["32", "28", "30", "26"], answer: 0, explain: "加 2、4、6、8、10。" },
  { id: "m127", cat: "math", grade: 12, q: "一盒 12 顆糖，3 盒有幾顆？", options: ["36", "15", "24", "30"], answer: 0, explain: "12×3。" },
  { id: "m128", cat: "math", grade: 12, q: "36 人平均分成 4 組，一組幾人？", options: ["9", "8", "6", "12"], answer: 0, explain: "36÷4。" },
  { id: "m129", cat: "math", grade: 12, q: "小華有 48 元，買 3 枝筆，一枝 9 元，剩下？", options: ["21", "27", "15", "39"], answer: 0, explain: "48-27=21。" },
  { id: "m130", cat: "math", grade: 23, q: "長方形長 8、寬 5，周長是？", options: ["26", "40", "13", "20"], answer: 0, explain: "（8+5）×2=26。" },
  { id: "m131", cat: "math", grade: 12, q: "正方形邊長 6，周長是？", options: ["24", "36", "12", "18"], answer: 0, explain: "6×4。" },
  { id: "m132", cat: "math", grade: 12, q: "現在 3 點，再過 2 小時是？", options: ["5 點", "4 點", "6 點", "1 點"], answer: 0, explain: "3+2。" },
  { id: "m133", cat: "math", grade: 12, q: "一小時有 60 分鐘。2 小時有幾分鐘？", options: ["120", "80", "100", "62"], answer: 0, explain: "60×2。" },
  { id: "m134", cat: "math", grade: 23, q: "7 個人每兩人握一次手，共握幾次？（每對一次）", options: ["21", "14", "7", "49"], answer: 0, explain: "C(7,2)=21。" },
  { id: "m135", cat: "math", grade: 23, q: "從 1 加到 10 等於？", options: ["55", "45", "50", "65"], answer: 0, explain: "10×11/2。" },
  { id: "m136", cat: "math", grade: 12, q: "一個數加上 8 等於 20，這個數是？", options: ["12", "28", "8", "10"], answer: 0, explain: "20-8。" },
  { id: "m137", cat: "math", grade: 12, q: "□ × 6 ＝ 42，□ 是？", options: ["7", "6", "8", "5"], answer: 0, explain: "42÷6。" },
  { id: "m138", cat: "math", grade: 12, q: "比 100 少 25 是？", options: ["75", "125", "80", "85"], answer: 0, explain: "100-25。" },
  { id: "m139", cat: "math", grade: 12, q: "3 個 15 是多少？", options: ["45", "18", "35", "53"], answer: 0, explain: "15×3。" },
  { id: "m140", cat: "math", grade: 12, q: "雞 2 隻腳、兔子 4 隻腳。2 雞 3 兔共幾隻腳？", options: ["16", "14", "12", "20"], answer: 0, explain: "4+12=16。" },
  { id: "m141", cat: "math", grade: 23, q: "路長 10 公尺，每隔 2 公尺種一棵（含兩端），種幾棵？", options: ["6", "5", "4", "10"], answer: 0, explain: "10/2+1=6。" },
  { id: "m142", cat: "math", grade: 12, q: "一排座位 8 個，已坐 3 人，還空？", options: ["5", "11", "8", "3"], answer: 0, explain: "8-3。" },
  { id: "m143", cat: "math", grade: 12, q: "糖果 25 顆，給弟弟 8 顆、妹妹 7 顆，自己剩？", options: ["10", "15", "9", "12"], answer: 0, explain: "25-8-7。" },
  { id: "m144", cat: "math", grade: 12, q: "9 的 4 倍是？", options: ["36", "13", "32", "45"], answer: 0, explain: "9×4。" },
  { id: "m145", cat: "math", grade: 12, q: "一半的 16 是？", options: ["8", "32", "4", "12"], answer: 0, explain: "16÷2。" },
  { id: "m146", cat: "math", grade: 23, q: "先算出來再比：哪個最大？", options: ["5×5", "3×8", "2×12", "4×6"], answer: 0, explain: "25 最大，另外三個都是 24。" },
  { id: "m147", cat: "math", grade: 23, q: "2＋3×4 等於？（先乘後加）", options: ["14", "20", "24", "11"], answer: 0, explain: "2+12=14。" },
  { id: "m148", cat: "math", grade: 12, q: "缺數：5、10、15、□、25", options: ["20", "16", "18", "22"], answer: 0, explain: "每次加 5。" },
  { id: "m149", cat: "math", grade: 12, q: "一個披萨切成 8 片，吃了 3 片，剩幾片？", options: ["5", "11", "8", "3"], answer: 0, explain: "8-3。" },
  { id: "m150", cat: "math", grade: 12, q: "3 個小朋友平分 18 顆糖，每人幾顆？", options: ["6", "15", "21", "9"], answer: 0, explain: "18÷3。" },
  { id: "m151", cat: "math", grade: 12, q: "最重的是？ 1 公斤棉花 和 1 公斤鐵", options: ["一樣重", "鐵", "棉花", "看體積"], answer: 0, explain: "都是 1 公斤。" },
  { id: "m152", cat: "math", grade: 23, q: "一杯水平均倒進 3 個空小杯，每小杯是原來的多少？", options: ["三分之一杯", "一杯", "三杯", "半杯"], answer: 0, explain: "1÷3。" },
  { id: "m153", cat: "math", grade: 23, q: "班級 28 人，男生比女生多 4 人。女生幾人？", options: ["12", "16", "14", "10"], answer: 0, explain: "女 x、男 x+4，2x+4=28，x=12。" },
  { id: "m154", cat: "math", grade: 12, q: "買 2 盒，每盒 4 排，每排 5 枝，共幾枝鉛筆？", options: ["40", "20", "10", "45"], answer: 0, explain: "2×4×5。" },
  { id: "m155", cat: "math", grade: 23, q: "用數字 8、8、3 排出一個三位數，最大是？", options: ["883", "838", "388", "833"], answer: 0, explain: "百位、十位先放大的 8。" },
  { id: "m156", cat: "math", grade: 12, q: "今天星期二，再過 8 天是星期幾？", options: ["三", "一", "四", "日"], answer: 0, explain: "8=7+1，星期二再 1 天是三。" },
  { id: "m157", cat: "math", grade: 12, q: "時針走一圈是 12 小時。從 2 點到 8 點走了幾小時？", options: ["6", "10", "8", "4"], answer: 0, explain: "8-2。" },
  { id: "m158", cat: "math", grade: 12, q: "□＋□＋□＝15，每個□相同，□是？", options: ["5", "3", "15", "6"], answer: 0, explain: "15÷3。" },
  { id: "m159", cat: "math", grade: 12, q: "比 36 多 9 的數，再減 5，得？", options: ["40", "30", "50", "22"], answer: 0, explain: "36+9-5=40。" },
  { id: "m160", cat: "math", grade: 23, q: "4 個連續整數和是 14，最小的是？", options: ["2", "1", "3", "4"], answer: 0, explain: "2+3+4+5=14。" },
  { id: "m161", cat: "math", grade: 12, q: "若 ▲＝3、●＝5，▲＋●＋▲＝？", options: ["11", "8", "15", "35"], answer: 0, explain: "3+5+3。" },
  { id: "m162", cat: "math", grade: 12, q: "一個 △ 代表 2。三個 △ 加起來是多少？", options: ["6", "24", "5", "3"], answer: 0, explain: "2+2+2＝6。" },
  { id: "ms12-1", cat: "math", grade: 12, q: "數列下一個：2、4、6、8、？", options: ["10", "11", "9", "12"], answer: 0, explain: "每次加 2" },
  { id: "ms12-2", cat: "math", grade: 12, q: "數列下一個：5、10、15、20、？", options: ["25", "26", "24", "27"], answer: 0, explain: "每次加 5" },
  { id: "ms12-3", cat: "math", grade: 12, q: "數列下一個：9、8、7、6、？", options: ["5", "6", "4", "7"], answer: 0, explain: "每次減 1" },
  { id: "ms12-4", cat: "math", grade: 12, q: "數列下一個：1、3、5、7、？", options: ["9", "10", "8", "11"], answer: 0, explain: "每次加 2 的奇數" },
  { id: "ms12-5", cat: "math", grade: 12, q: "數列下一個：10、20、30、40、？", options: ["50", "51", "49", "52"], answer: 0, explain: "每次加 10" },
  { id: "ms12-6", cat: "math", grade: 12, q: "數列下一個：3、6、9、12、？", options: ["15", "16", "14", "17"], answer: 0, explain: "每次加 3" },
  { id: "ms12-7", cat: "math", grade: 12, q: "數列下一個：4、8、12、16、？", options: ["20", "21", "19", "22"], answer: 0, explain: "每次加 4" },
  { id: "ms12-8", cat: "math", grade: 12, q: "數列下一個：20、18、16、14、？", options: ["12", "13", "11", "14"], answer: 0, explain: "每次減 2" },
  { id: "ms23-9", cat: "math", grade: 23, q: "數列下一個：1、2、4、8、？", options: ["16", "17", "15", "18"], answer: 0, explain: "每次乘 2" },
  { id: "ms23-10", cat: "math", grade: 23, q: "數列下一個：3、6、12、24、？", options: ["48", "49", "47", "50"], answer: 0, explain: "每次乘 2" },
  { id: "ms23-11", cat: "math", grade: 23, q: "數列下一個：1、3、6、10、？", options: ["15", "16", "14", "17"], answer: 0, explain: "加 2、3、4、5" },
  { id: "ms23-12", cat: "math", grade: 23, q: "數列下一個：2、6、12、20、？", options: ["30", "31", "29", "32"], answer: 0, explain: "加 4、6、8、10" },
  { id: "ms23-13", cat: "math", grade: 23, q: "數列下一個：81、27、9、3、？", options: ["1", "2", "3", "4"], answer: 0, explain: "每次除以 3" },
  { id: "ms23-14", cat: "math", grade: 23, q: "數列下一個：2、3、5、8、？", options: ["13", "14", "12", "15"], answer: 0, explain: "前兩項相加" },
  { id: "ms23-15", cat: "math", grade: 23, q: "數列下一個：1、4、9、16、？", options: ["25", "26", "24", "27"], answer: 0, explain: "平方數" },
  { id: "ms23-16", cat: "math", grade: 23, q: "數列下一個：5、10、20、40、？", options: ["80", "81", "79", "82"], answer: 0, explain: "每次乘 2" },
  { id: "ms34-17", cat: "math", grade: 34, q: "數列下一個：2、5、11、23、？", options: ["47", "48", "46", "49"], answer: 0, explain: "乘 2 再加 1" },
  { id: "ms34-18", cat: "math", grade: 34, q: "數列下一個：3、4、6、9、13、？", options: ["18", "19", "17", "20"], answer: 0, explain: "加 1、2、3、4、5" },
  { id: "ms34-19", cat: "math", grade: 34, q: "數列下一個：100、91、82、73、？", options: ["64", "65", "63", "66"], answer: 0, explain: "每次減 9" },
  { id: "ms34-20", cat: "math", grade: 34, q: "數列下一個：1、8、27、64、？", options: ["125", "126", "124", "127"], answer: 0, explain: "立方：1³ 2³ 3³ 4³ 5³" },
  { id: "ms34-21", cat: "math", grade: 34, q: "數列下一個：2、6、18、54、？", options: ["162", "163", "161", "164"], answer: 0, explain: "每次乘 3" },
  { id: "ms34-22", cat: "math", grade: 34, q: "數列下一個：1、1、2、3、5、8、？", options: ["13", "14", "12", "15"], answer: 0, explain: "費氏數列" },
  { id: "ms34-23", cat: "math", grade: 34, q: "數列下一個：12、15、19、24、？", options: ["30", "31", "29", "32"], answer: 0, explain: "加 3、4、5、6" },
  { id: "ms34-24", cat: "math", grade: 34, q: "數列下一個：64、32、16、8、？", options: ["4", "5", "3", "6"], answer: 0, explain: "每次除以 2" },
  { id: "ms56-25", cat: "math", grade: 56, q: "數列下一個：2、6、12、20、30、？", options: ["42", "43", "41", "44"], answer: 0, explain: "加 4、6、8、10、12" },
  { id: "ms56-26", cat: "math", grade: 56, q: "數列下一個：3、9、27、81、？", options: ["243", "244", "242", "245"], answer: 0, explain: "每次乘 3" },
  { id: "ms56-27", cat: "math", grade: 56, q: "數列下一個：1、4、10、22、？", options: ["46", "47", "45", "48"], answer: 0, explain: "乘 2 再加 2" },
  { id: "ms56-28", cat: "math", grade: 56, q: "數列下一個：5、6、8、11、15、？", options: ["20", "21", "19", "22"], answer: 0, explain: "加 1、2、3、4、5" },
  { id: "ms56-29", cat: "math", grade: 56, q: "數列下一個：2、3、5、9、17、？", options: ["33", "34", "32", "35"], answer: 0, explain: "乘 2 減 1" },
  { id: "ms56-30", cat: "math", grade: 56, q: "數列下一個：1、2、6、24、？", options: ["120", "121", "119", "122"], answer: 0, explain: "乘 2、3、4、5" },
  { id: "ms56-31", cat: "math", grade: 56, q: "數列下一個：10、11、13、16、20、？", options: ["25", "26", "24", "27"], answer: 0, explain: "加 1、2、3、4、5" },
  { id: "ms56-32", cat: "math", grade: 56, q: "數列下一個：81、27、9、3、？", options: ["1", "2", "3", "4"], answer: 0, explain: "每次除以 3" },
  { id: "m12w1", cat: "math", grade: 12, q: "一盒 8 顆糖，2 盒有幾顆？", options: ["16", "10", "6", "18"], answer: 0, explain: "8×2" },
  { id: "m12w2", cat: "math", grade: 12, q: "15 顆分給 3 人，每人幾顆？", options: ["5", "12", "18", "3"], answer: 0, explain: "15÷3" },
  { id: "m12w3", cat: "math", grade: 12, q: "小華有 20 元，花 7 元，剩？", options: ["13", "27", "17", "14"], answer: 0, explain: "20-7" },
  { id: "m12w4", cat: "math", grade: 12, q: "現在 4 點，再過 3 小時？", options: ["7 點", "6 點", "1 點", "8 點"], answer: 0, explain: "4+3" },
  { id: "m12w5", cat: "math", grade: 12, q: "一半的 12 是？", options: ["6", "24", "10", "2"], answer: 0, explain: "12÷2" },
  { id: "m12w6", cat: "math", grade: 12, q: "9 的 2 倍是？", options: ["18", "11", "7", "27"], answer: 0, explain: "9×2" },
  { id: "m12w7", cat: "math", grade: 12, q: "比 30 多 8 是？", options: ["38", "22", "308", "32"], answer: 0, explain: "30+8" },
  { id: "m12w8", cat: "math", grade: 12, q: "正方形邊長 4，周長？", options: ["16", "8", "12", "20"], answer: 0, explain: "4×4" },
  { id: "m23w1", cat: "math", grade: 23, q: "長方形長 7、寬 4，周長？", options: ["22", "28", "11", "18"], answer: 0, explain: "（7+4）×2" },
  { id: "m23w2", cat: "math", grade: 23, q: "48 元買 4 枝筆，一枝 9 元，剩？", options: ["12", "36", "13", "44"], answer: 0, explain: "48-36" },
  { id: "m23w3", cat: "math", grade: 23, q: "雞 2 腳兔 4 腳。3 雞 2 兔共幾腳？", options: ["14", "12", "16", "10"], answer: 0, explain: "6+8" },
  { id: "m23w4", cat: "math", grade: 23, q: "路長 8 公尺，每隔 2 公尺種一棵（含兩端），幾棵？", options: ["5", "4", "6", "8"], answer: 0, explain: "8/2+1" },
  { id: "m23w5", cat: "math", grade: 23, q: "2＋3×5（先乘後加）？", options: ["17", "25", "10", "13"], answer: 0, explain: "2+15" },
  { id: "m23w6", cat: "math", grade: 23, q: "男生比女生多 6 人，全班 30 人，女生？", options: ["12", "18", "15", "24"], answer: 0, explain: "女 x、男 x+6，2x+6=30" },
  { id: "m23w7", cat: "math", grade: 23, q: "今天星期三，再過 10 天星期幾？", options: ["六", "日", "五", "一"], answer: 0, explain: "10=7+3，三再 3 天是六" },
  { id: "m23w8", cat: "math", grade: 23, q: "3 個連續整數和是 12，最小的是？", options: ["3", "2", "4", "1"], answer: 0, explain: "3+4+5" },
  { id: "m34w1", cat: "math", grade: 34, q: "長 12、寬 8 的長方形面積？", options: ["96", "40", "20", "80"], answer: 0, explain: "12×8" },
  { id: "m34w2", cat: "math", grade: 34, q: "1/2 + 1/4 等於？", options: ["3/4", "2/6", "1/6", "1"], answer: 0, explain: "通分 2/4+1/4" },
  { id: "m34w3", cat: "math", grade: 34, q: "一本書 240 頁，讀了 1/3，還剩幾頁？", options: ["160", "80", "200", "120"], answer: 0, explain: "240-80" },
  { id: "m34w4", cat: "math", grade: 34, q: "平均：80、90、70，平均多少？", options: ["80", "240", "75", "90"], answer: 0, explain: "240÷3" },
  { id: "m34w5", cat: "math", grade: 34, q: "時針 2 點到 8 點走幾小時？", options: ["6", "10", "8", "4"], answer: 0, explain: "8-2" },
  { id: "m34w6", cat: "math", grade: 34, q: "一個數的 4 倍是 72，這個數？", options: ["18", "68", "288", "76"], answer: 0, explain: "72÷4" },
  { id: "m34w7", cat: "math", grade: 34, q: "圓的 1/4 再對半，是整個圓的？", options: ["1/8", "1/2", "1/6", "1/4"], answer: 0, explain: "1/4×1/2" },
  { id: "m34w8", cat: "math", grade: 34, q: "7 人每兩人握一次手（每對一次），幾次？", options: ["21", "14", "7", "49"], answer: 0, explain: "7×6/2" },
  { id: "m56w1", cat: "math", grade: 56, q: "汽車 3 小時走 180 公里。平均一小時走幾公里？", options: ["60", "540", "177", "90"], answer: 0, explain: "180÷3＝60。" },
  { id: "m56w2", cat: "math", grade: 56, q: "一打 12 枝。2 打半是幾枝？", options: ["30", "24", "26", "36"], answer: 0, explain: "24+6" },
  { id: "m56w3", cat: "math", grade: 56, q: "甲和乙的比是 3 比 2。甲是 15 時，乙是多少？", options: ["10", "13", "6", "30"], answer: 0, explain: "15÷3×2＝10。" },
  { id: "m56w4", cat: "math", grade: 56, q: "0.5 + 0.25 等於？", options: ["0.75", "0.7", "0.025", "2.5"], answer: 0, explain: "1/2+1/4" },
  { id: "m56w5", cat: "math", grade: 56, q: "因數：12 的正因數有幾個？（含 1 和 12）", options: ["6", "4", "8", "3"], answer: 0, explain: "1,2,3,4,6,12" },
  { id: "m56w6", cat: "math", grade: 56, q: "一折 8 折。原價 200 元，現價？", options: ["160", "192", "208", "25"], answer: 0, explain: "200×0.8" },
  { id: "m56w7", cat: "math", grade: 56, q: "從 1 加到 20？", options: ["210", "200", "190", "220"], answer: 0, explain: "20×21/2" },
  { id: "m56w8", cat: "math", grade: 56, q: "長 10、寬 6 的長方形，剪掉一個邊長 2 的正方形，剩面積？", options: ["56", "60", "58", "52"], answer: 0, explain: "60-4" },
  { id: "l12a1", cat: "lang", grade: 12, q: "「大」的相反？", options: ["小", "多", "高", "長"], answer: 0, explain: "反義" },
  { id: "l12a2", cat: "lang", grade: 12, q: "眼睛：看＝鼻子：？", options: ["聞", "走", "聽", "說"], answer: 0, explain: "器官功能" },
  { id: "l12a3", cat: "lang", grade: 12, q: "哪一個不同類？", options: ["桌子", "蘋果", "香蕉", "葡萄"], answer: 0, explain: "桌子不是水果" },
  { id: "l12a4", cat: "lang", grade: 12, q: "量詞：一（　）貓", options: ["隻", "本", "朵", "輛"], answer: 0, explain: "動物常用隻" },
  { id: "l12a5", cat: "lang", grade: 12, q: "「因為下雨，所以……」最合理？", options: ["帶傘或待在屋裡", "去游泳不帶傘", "把書放外面", "關燈就停雨"], answer: 0, explain: "因果" },
  { id: "l12a6", cat: "lang", grade: 12, q: "「上面」的相反？", options: ["下面", "裡面", "左邊", "前面"], answer: 0, explain: "方位" },
  { id: "l23a1", cat: "lang", grade: 23, q: "筆：寫＝尺：？", options: ["量", "切", "唱", "跑"], answer: 0, explain: "工具用途" },
  { id: "l23a2", cat: "lang", grade: 23, q: "「開始」的相反？", options: ["結束", "繼續", "出發", "起點"], answer: 0, explain: "反義" },
  { id: "l23a3", cat: "lang", grade: 23, q: "「一石二鳥」較接近？", options: ["一件事兩種好處", "真的打兩隻鳥", "不能同時做事", "要用力"], answer: 0, explain: "成語比喻" },
  { id: "l23a4", cat: "lang", grade: 23, q: "「在／再」：請（　）說一次", options: ["再", "在", "怎", "只"], answer: 0, explain: "再＝又一次" },
  { id: "l23a5", cat: "lang", grade: 23, q: "「專心」最接近？", options: ["注意力放在一件事", "同時做十件事", "一直說話", "到處走"], answer: 0, explain: "詞義" },
  { id: "l23a6", cat: "lang", grade: 23, q: "老師：學校＝廚師：？", options: ["廚房或餐廳", "醫院", "車站", "球場"], answer: 0, explain: "職業場所" },
  { id: "l34a1", cat: "lang", grade: 34, q: "溫度：溫度計＝時間：？", options: ["時鐘", "天氣", "數字", "太陽"], answer: 0, explain: "測量工具" },
  { id: "l34a2", cat: "lang", grade: 34, q: "「雪中送炭」較接近？", options: ["在別人困難時幫忙", "冬天烤火", "送黑色的炭", "下雪不能出門"], answer: 0, explain: "成語" },
  { id: "l34a3", cat: "lang", grade: 34, q: "「但是」通常用來？", options: ["轉折、說另一面", "完全重複前面", "問路", "數數字"], answer: 0, explain: "連接詞" },
  { id: "l34a4", cat: "lang", grade: 34, q: "「默默」最接近？", options: ["不說話、安靜地", "很大聲", "很快", "很亮"], answer: 0, explain: "詞義" },
  { id: "l34a5", cat: "lang", grade: 34, q: "原因：結果＝播種：？", options: ["收成", "下雨", "書包", "星期一"], answer: 0, explain: "先因後果" },
  { id: "l34a6", cat: "lang", grade: 34, q: "哪一句最客觀？", options: ["水在 0 度會結冰（一般情況）", "我最討厭數學", "這一定是全世界最好吃", "他永遠不會錯"], answer: 0, explain: "可檢驗的事實" },
  { id: "l34a7", cat: "lang", grade: 34, q: "「井底之蛙」比喻？", options: ["見識狹窄", "很會游泳", "住在井裡很好", "青蛙很多"], answer: 0, explain: "成語" },
  { id: "l34a8", cat: "lang", grade: 34, q: "「預測」最接近？", options: ["根據線索猜未來可能", "已經發生的事", "隨便亂講", "只回憶昨天"], answer: 0, explain: "詞義" },
  { id: "l56a1", cat: "lang", grade: 56, q: "光合作用：植物＝呼吸：？", options: ["動物或生物", "石頭", "雲", "數字"], answer: 0, explain: "生命基本作用" },
  { id: "l56a2", cat: "lang", grade: 56, q: "「本末倒置」較接近？", options: ["把重要和不重要搞反", "樹長顛倒", "很會排隊", "計算很快"], answer: 0, explain: "成語" },
  { id: "l56a3", cat: "lang", grade: 56, q: "「風像刀子」這種說法，是把風比成刀。這叫什麼？", options: ["比喻（明喻）", "直接罵人", "只寫數字", "問路"], answer: 0, explain: "用「像」把兩件事連起來。" },
  { id: "l56a4", cat: "lang", grade: 56, q: "證據：結論＝實驗數據：？", options: ["科學推論", "心情", "運氣", "顏色"], answer: 0, explain: "論證關係" },
  { id: "l56a5", cat: "lang", grade: 56, q: "「矛盾」最接近？", options: ["兩件事對不上、互相衝突", "很和平", "同一句話", "只有一個答案"], answer: 0, explain: "詞義" },
  { id: "l56a6", cat: "lang", grade: 56, q: "作者寫「風像刀子」主要想寫？", options: ["風很冷、很利", "真的有刀從天降", "風會切菜", "要買刀"], answer: 0, explain: "修辭" },
  { id: "l56a7", cat: "lang", grade: 56, q: "「批判思考」較接近？", options: ["先問證據再下判斷", "別人說什麼都信", "永遠反對", "不看書"], answer: 0, explain: "概念" },
  { id: "l56a8", cat: "lang", grade: 56, q: "地圖：地方＝食譜：？", options: ["料理步驟", "冰箱", "筷子", "餐桌"], answer: 0, explain: "對照說明" },
  { id: "g12f1", cat: "fig", grade: 12, q: "哪一個不同類？", options: ["▲▲●", "○○○", "■■■", "△△△"], answer: 0, explain: "其他三個都是三個相同" },
  { id: "g12f2", cat: "fig", grade: 12, q: "找出下一個：● ▲ ● ▲ ● ？", options: ["▲", "●", "■", "○"], answer: 0, explain: "兩種輪流" },
  { id: "g12f3", cat: "fig", grade: 12, q: "實心 ▲ 對應空心 △，實心 ● 對應？", options: ["○", "■", "▲", "◆"], answer: 0, explain: "實心變空心" },
  { id: "g12f4", cat: "fig", grade: 12, q: "左右對摺會重疊的是？", options: ["○", "L", "P", "F"], answer: 0, explain: "圓左右對稱" },
  { id: "g12f5", cat: "fig", grade: 12, q: "影子在左，光源在？", options: ["右邊", "左邊", "上邊", "下邊"], answer: 0, explain: "光源與影子相對" },
  { id: "g23f1", cat: "fig", grade: 23, q: "↑ 順時針 90 度變成？", options: ["→", "←", "↑", "↓"], answer: 0, explain: "上變右" },
  { id: "g23f2", cat: "fig", grade: 23, q: "▲ 在 ■ 上方，整組順時針轉 90 度後，▲ 在 ■ 的？", options: ["右邊", "左邊", "上面", "下面"], answer: 0, explain: "上方轉到右方" },
  { id: "g23f3", cat: "fig", grade: 23, q: "點在圓內 對應 點在圓外。正方形在圓內 對應？", options: ["正方形在圓外", "圓在正方形內", "兩個圓", "空白"], answer: 0, explain: "裡外對調" },
  { id: "g23f4", cat: "fig", grade: 23, q: "四個正方形排成一長條，能不能折成正方體？", options: ["不能", "能", "不一定", "只能折成長方體"], answer: 0, explain: "一列四格包不住" },
  { id: "g23f5", cat: "fig", grade: 23, q: "三點不共線，兩兩連線最多幾條直線？", options: ["3", "1", "2", "4"], answer: 0, explain: "C(3,2)=3" },
  { id: "g34f1", cat: "fig", grade: 34, q: "九宮格：黑點從左上→中上→右上。下一步最可能？", options: ["右中", "左下", "正中", "消失"], answer: 0, explain: "先走完上列再往下右" },
  { id: "g34f2", cat: "fig", grade: 34, q: "從上看正方體看到正方形。從旁邊看長方體（較長）最可能看到？", options: ["長方形", "圓", "正三角形", "一點"], answer: 0, explain: "側面是長方形" },
  { id: "g34f3", cat: "fig", grade: 34, q: "紙對摺一次剪一洞（沒剪摺線），打開幾個洞？", options: ["2", "1", "3", "4"], answer: 0, explain: "兩層各一" },
  { id: "g34f4", cat: "fig", grade: 34, q: "字母 L 每次順時針轉 90 度。轉兩次（共 180 度）後，最像哪一個？", options: ["倒過來的 L", "＋", "○", "還是原來的 L"], answer: 0, explain: "轉兩次等於上下顛倒。" },
  { id: "g34f5", cat: "fig", grade: 34, q: "2×2 格子只能往右或往上，從左下到右上（兩右兩上）走法？", options: ["6", "4", "2", "8"], answer: 0, explain: "C(4,2)=6" },
  { id: "g34f6", cat: "fig", grade: 34, q: "外圓內方 對應 外方內圓。外三角內圓 對應？", options: ["外圓內三角", "外三角內三角", "兩個圓", "空白"], answer: 0, explain: "外內對調" },
  { id: "g34f7", cat: "fig", grade: 34, q: "一筆畫：正方形四邊能不能每邊只畫一次、筆不離開？", options: ["可以", "不可以", "只能三邊", "一定要重複"], answer: 0, explain: "四邊形一筆畫可" },
  { id: "g34f8", cat: "fig", grade: 34, q: "鏡子在右邊，字母 b 的左右鏡像最接近？", options: ["d", "p", "q", "b"], answer: 0, explain: "左右翻" },
  { id: "g56f1", cat: "fig", grade: 56, q: "六個正方形：中間一列三個，上面中間再接一個、下面中間再接一個（像十字再多一格）。這樣能不能折成正方體？", options: ["能", "不能", "會變成球", "沒有正方形"], answer: 0, explain: "這種展開圖可以折成正方體。" },
  { id: "g56f2", cat: "fig", grade: 56, q: "矩陣：每列黑色往右一格。第一列黑在左，第二列黑在中，第三列黑在？", options: ["右", "左", "中", "三格全黑"], answer: 0, explain: "右移" },
  { id: "g56f3", cat: "fig", grade: 56, q: "俯視 2×2 都有積木，一格堆 4 塊、其餘各 1，一共？", options: ["7", "6", "8", "5"], answer: 0, explain: "4+1+1+1" },
  { id: "g56f4", cat: "fig", grade: 56, q: "長方形（長大於寬）對稱軸有幾條？", options: ["2", "4", "1", "0"], answer: 0, explain: "橫直各一，沒有對角線" },
  { id: "g56f5", cat: "fig", grade: 56, q: "圖：每次邊數加 1。△（3）→□（4）→五邊形（5）→？", options: ["六邊形", "圓", "還是五邊", "兩條線"], answer: 0, explain: "邊數+1" },
  { id: "g56f6", cat: "fig", grade: 56, q: "一個立體從正面看是正方形，從上面看也是正方形。它最可能是什麼？", options: ["正方體", "球", "圓柱", "三角形積木"], answer: 0, explain: "正方體各面都是正方形。" },
  { id: "g56f7", cat: "fig", grade: 56, q: "旋轉 90 度四次會？", options: ["回到原圖", "變成鏡像停住", "消失", "面積變兩倍"], answer: 0, explain: "360 度" },
  { id: "g56f8", cat: "fig", grade: 56, q: "網路路徑：A 連 B、B 連 C，不走回頭。A 到 C 最少幾步？", options: ["2", "1", "3", "0"], answer: 0, explain: "A-B-C" },
  { id: "e12-x9", cat: "mem", grade: 12, q: "記住：4、7。兩個加起來剛才是？", options: ["11", "47", "3", "74"], answer: 0, explain: "4+7" },
  { id: "e12-x10", cat: "mem", grade: 12, q: "記住動物序：雞、鴨、鵝。第一個？", options: ["雞", "鴨", "鵝", "鳥"], answer: 0, explain: "對照剛看過的順序" },
  { id: "e23-x11", cat: "mem", grade: 23, q: "記住：11、4、8。哪個最大？", options: ["11", "8", "4", "0"], answer: 0, explain: "對照剛看過的順序" },
  { id: "e23-x12", cat: "mem", grade: 23, q: "記住：★ ○ ★。星星出現幾次？", options: ["2", "1", "3", "0"], answer: 0, explain: "對照剛看過的順序" },
  { id: "e34-x13", cat: "mem", grade: 34, q: "記住：2、4、8、3。哪一個不是「每次乘 2」？", options: ["3", "2", "4", "8"], answer: 0, explain: "2×2＝4、4×2＝8，3 不是 8 的兩倍。" },
  { id: "e34-x14", cat: "mem", grade: 34, q: "記住五色：紅橙黃綠藍。第四個？", options: ["綠", "紅", "藍", "橙"], answer: 0, explain: "對照剛看過的順序" },
  { id: "e56-x15", cat: "mem", grade: 56, q: "記住：9、4、1、6、2、8、5。第 2 個＋第 7 個？", options: ["9", "13", "6", "7"], answer: 0, explain: "4+5" },
  { id: "e56-x16", cat: "mem", grade: 56, q: "記住：甲乙丙丁戊。倒數第二個？", options: ["丁", "戊", "丙", "甲"], answer: 0, explain: "對照剛看過的順序" },
  { id: "e12-1", cat: "mem", grade: 12, q: "記住這串數字：2、9、4。倒過來是？", options: ["4、9、2", "2、9、4", "9、2、4", "4、2、9"], answer: 0, explain: "從後面唸回來" },
  { id: "e12-2", cat: "mem", grade: 12, q: "記住：▲ ● ■。中間那個是？", options: ["●", "▲", "■", "○"], answer: 0, explain: "第二個" },
  { id: "e12-3", cat: "mem", grade: 12, q: "記住：5、1、8。第一個是？", options: ["5", "1", "8", "0"], answer: 0, explain: "開頭" },
  { id: "e12-4", cat: "mem", grade: 12, q: "記住顏色順序：紅、藍、黃。最後一個？", options: ["黃", "紅", "藍", "綠"], answer: 0, explain: "第三個" },
  { id: "e12-5", cat: "mem", grade: 12, q: "記住：3、3、7。出現兩次的數字是？", options: ["3", "7", "0", "1"], answer: 0, explain: "3 出現兩次" },
  { id: "e12-6", cat: "mem", grade: 12, q: "記住：大、中、小。倒過來？", options: ["小、中、大", "大、中、小", "中、大、小", "小、大、中"], answer: 0, explain: "倒序" },
  { id: "e12-7", cat: "mem", grade: 12, q: "記住四個：1、6、2、8。第二個是？", options: ["6", "1", "2", "8"], answer: 0, explain: "位置 2" },
  { id: "e12-8", cat: "mem", grade: 12, q: "記住：貓、狗、鳥。沒有出現的是？", options: ["魚", "貓", "狗", "鳥"], answer: 0, explain: "題幹沒有魚" },
  { id: "e23-1", cat: "mem", grade: 23, q: "記住：7、2、9、4。倒過來？", options: ["4、9、2、7", "7、2、9、4", "9、4、7、2", "2、7、4、9"], answer: 0, explain: "倒序" },
  { id: "e23-2", cat: "mem", grade: 23, q: "記住：○ △ □ ★。第三個？", options: ["□", "○", "△", "★"], answer: 0, explain: "位置 3" },
  { id: "e23-3", cat: "mem", grade: 23, q: "記住：8、1、8、3。哪個數字出現兩次？", options: ["8", "1", "3", "0"], answer: 0, explain: "8" },
  { id: "e23-4", cat: "mem", grade: 23, q: "記住：北、東、南。缺了哪個方位最常見的一組？", options: ["西", "上", "中", "裡"], answer: 0, explain: "東西南北" },
  { id: "e23-5", cat: "mem", grade: 23, q: "記住五個：2、5、9、1、6。最後一個？", options: ["6", "2", "5", "1"], answer: 0, explain: "末項" },
  { id: "e23-6", cat: "mem", grade: 23, q: "記住：A、C、E。下一個字母若依隔一個？", options: ["G", "F", "D", "B"], answer: 0, explain: "A C E G" },
  { id: "e23-7", cat: "mem", grade: 23, q: "記住：3、0、5、1。倒過來從後面唸是？", options: ["1、5、0、3", "3、0、5、1", "0、3、1、5", "5、1、3、0"], answer: 0, explain: "從最後一個往回唸：1、5、0、3。" },
  { id: "e23-8", cat: "mem", grade: 23, q: "記住：左、上、右。沒有的是？", options: ["下", "左", "上", "右"], answer: 0, explain: "缺下" },
  { id: "e34-1", cat: "mem", grade: 34, q: "記住：4、9、1、7、2。倒過來前三個？", options: ["2、7、1", "4、9、1", "9、1、7", "1、7、2"], answer: 0, explain: "從尾端 2,7,1" },
  { id: "e34-2", cat: "mem", grade: 34, q: "記住：紅圓、藍方、黃三角、綠星。第二個形狀？", options: ["方", "圓", "三角", "星"], answer: 0, explain: "藍方" },
  { id: "e34-3", cat: "mem", grade: 34, q: "記住：6、2、6、8、6。出現最多次的是？", options: ["6", "2", "8", "0"], answer: 0, explain: "三次 6" },
  { id: "e34-4", cat: "mem", grade: 34, q: "記住：3、8、1、4、9、2。第 5 個？", options: ["9", "3", "4", "2"], answer: 0, explain: "位置 5" },
  { id: "e34-5", cat: "mem", grade: 34, q: "英文字母順序：K 的下下個是 M，M 的下下個是 P。P 的下下個是？", options: ["R", "Q", "O", "S"], answer: 0, explain: "每次跳過一個字母：P 下一是 Q，再下是 R。" },
  { id: "e34-6", cat: "mem", grade: 34, q: "記住方向順序：上、右、下、左。這比較像哪一種轉法？", options: ["順時針轉一圈的方向", "隨機", "只有上下", "數字"], answer: 0, explain: "上→右→下→左是順時針。" },
  { id: "e34-7", cat: "mem", grade: 34, q: "記住兩組：A＝2、B＝5。問剛才 B 是？", options: ["5", "2", "7", "0"], answer: 0, explain: "對照" },
  { id: "e34-8", cat: "mem", grade: 34, q: "記住：9、0、4、4、1。沒有出現的數字？", options: ["2", "9", "0", "4"], answer: 0, explain: "2 未出現" },
  { id: "e56-1", cat: "mem", grade: 56, q: "記住：5、1、9、3、7、2。倒過來前三個？", options: ["2、7、3", "5、1、9", "1、9、3", "7、2、5"], answer: 0, explain: "尾端" },
  { id: "e56-2", cat: "mem", grade: 56, q: "記住：L、3、K、8、M。第 4 個？", options: ["8", "L", "K", "M"], answer: 0, explain: "數字 8" },
  { id: "e56-3", cat: "mem", grade: 56, q: "記住：2、8、2、8、9。前面都是 2、8 反覆，最後一個換成什麼？", options: ["9", "2", "8", "0"], answer: 0, explain: "最後一個不是 2 也不是 8，是 9。" },
  { id: "e56-4", cat: "mem", grade: 56, q: "記住七項：1、4、9、2、6、5、3。第 6 個？", options: ["5", "6", "3", "2"], answer: 0, explain: "位置 6" },
  { id: "e56-5", cat: "mem", grade: 56, q: "記住：北、西、南、東。這順序較像？", options: ["逆時針繞方位", "只往北", "隨機顏色", "加減法"], answer: 0, explain: "北→西→南→東" },
  { id: "e56-6", cat: "mem", grade: 56, q: "記住：A1、B2、C3。D 對應？", options: ["4", "D", "1", "5"], answer: 0, explain: "字母序對數字序" },
  { id: "e56-7", cat: "mem", grade: 56, q: "記住：7、1、8、2、9。中間那個？", options: ["8", "7", "1", "9"], answer: 0, explain: "第三個" },
  { id: "e56-8", cat: "mem", grade: 56, q: "記住：△○□△○。下一個若循環？", options: ["□", "△", "○", "★"], answer: 0, explain: "三個一循環" },
  { id: "mf12-0", cat: "math", grade: 12, q: "2 個小朋友每人 5 顆糖，一共幾顆？", options: ["10", "7", "3", "11"], answer: 0, explain: "2×5" },
  { id: "mf12-1", cat: "math", grade: 12, q: "3 個小朋友每人 6 顆糖，一共幾顆？", options: ["18", "9", "3", "19"], answer: 0, explain: "3×6" },
  { id: "mf12-2", cat: "math", grade: 12, q: "4 個小朋友每人 7 顆糖，一共幾顆？", options: ["28", "11", "3", "29"], answer: 0, explain: "4×7" },
  { id: "mf12-3", cat: "math", grade: 12, q: "5 個小朋友每人 8 顆糖，一共幾顆？", options: ["40", "13", "3", "41"], answer: 0, explain: "5×8" },
  { id: "mf12-4", cat: "math", grade: 12, q: "6 個小朋友每人 9 顆糖，一共幾顆？", options: ["54", "15", "3", "55"], answer: 0, explain: "6×9" },
  { id: "mf12-5", cat: "math", grade: 12, q: "7 個小朋友每人 10 顆糖，一共幾顆？", options: ["70", "17", "3", "71"], answer: 0, explain: "7×10" },
  { id: "mf12-6", cat: "math", grade: 12, q: "8 個小朋友每人 11 顆糖，一共幾顆？", options: ["88", "19", "3", "89"], answer: 0, explain: "8×11" },
  { id: "mf12-7", cat: "math", grade: 12, q: "9 個小朋友每人 12 顆糖，一共幾顆？", options: ["108", "21", "3", "109"], answer: 0, explain: "9×12" },
  { id: "mf12-8", cat: "math", grade: 12, q: "10 個小朋友每人 13 顆糖，一共幾顆？", options: ["130", "23", "3", "131"], answer: 0, explain: "10×13" },
  { id: "mf12-9", cat: "math", grade: 12, q: "11 個小朋友每人 14 顆糖，一共幾顆？", options: ["154", "25", "3", "155"], answer: 0, explain: "11×14" },
  { id: "mf12-10", cat: "math", grade: 12, q: "12 個小朋友每人 15 顆糖，一共幾顆？", options: ["180", "27", "3", "181"], answer: 0, explain: "12×15" },
  { id: "mf12-11", cat: "math", grade: 12, q: "13 個小朋友每人 16 顆糖，一共幾顆？", options: ["208", "29", "3", "209"], answer: 0, explain: "13×16" },
  { id: "mf23-0", cat: "math", grade: 23, q: "3 個小朋友每人 6 顆糖，一共幾顆？", options: ["18", "9", "3", "19"], answer: 0, explain: "3×6" },
  { id: "mf23-1", cat: "math", grade: 23, q: "5 個小朋友每人 7 顆糖，一共幾顆？", options: ["35", "12", "2", "36"], answer: 0, explain: "5×7" },
  { id: "mf23-2", cat: "math", grade: 23, q: "7 個小朋友每人 8 顆糖，一共幾顆？", options: ["56", "15", "1", "57"], answer: 0, explain: "7×8" },
  { id: "mf23-3", cat: "math", grade: 23, q: "9 個小朋友每人 9 顆糖，一共幾顆？", options: ["81", "18", "11", "82"], answer: 0, explain: "9×9" },
  { id: "mf23-4", cat: "math", grade: 23, q: "11 個小朋友每人 10 顆糖，一共幾顆？", options: ["110", "21", "1", "111"], answer: 0, explain: "11×10" },
  { id: "mf23-5", cat: "math", grade: 23, q: "13 個小朋友每人 11 顆糖，一共幾顆？", options: ["143", "24", "2", "144"], answer: 0, explain: "13×11" },
  { id: "mf23-6", cat: "math", grade: 23, q: "15 個小朋友每人 12 顆糖，一共幾顆？", options: ["180", "27", "3", "181"], answer: 0, explain: "15×12" },
  { id: "mf23-7", cat: "math", grade: 23, q: "17 個小朋友每人 13 顆糖，一共幾顆？", options: ["221", "30", "4", "222"], answer: 0, explain: "17×13" },
  { id: "mf23-8", cat: "math", grade: 23, q: "19 個小朋友每人 14 顆糖，一共幾顆？", options: ["266", "33", "5", "267"], answer: 0, explain: "19×14" },
  { id: "mf23-9", cat: "math", grade: 23, q: "21 個小朋友每人 15 顆糖，一共幾顆？", options: ["315", "36", "6", "316"], answer: 0, explain: "21×15" },
  { id: "mf23-10", cat: "math", grade: 23, q: "23 個小朋友每人 16 顆糖，一共幾顆？", options: ["368", "39", "7", "369"], answer: 0, explain: "23×16" },
  { id: "mf23-11", cat: "math", grade: 23, q: "25 個小朋友每人 17 顆糖，一共幾顆？", options: ["425", "42", "8", "426"], answer: 0, explain: "25×17" },
  { id: "mf34-0", cat: "math", grade: 34, q: "6 個小朋友每人 9 顆糖，一共幾顆？", options: ["54", "15", "3", "55"], answer: 0, explain: "6×9" },
  { id: "mf34-1", cat: "math", grade: 34, q: "9 個小朋友每人 10 顆糖，一共幾顆？", options: ["90", "19", "1", "91"], answer: 0, explain: "9×10" },
  { id: "mf34-2", cat: "math", grade: 34, q: "12 個小朋友每人 11 顆糖，一共幾顆？", options: ["132", "23", "1", "133"], answer: 0, explain: "12×11" },
  { id: "mf34-3", cat: "math", grade: 34, q: "15 個小朋友每人 12 顆糖，一共幾顆？", options: ["180", "27", "3", "181"], answer: 0, explain: "15×12" },
  { id: "mf34-4", cat: "math", grade: 34, q: "18 個小朋友每人 13 顆糖，一共幾顆？", options: ["234", "31", "5", "235"], answer: 0, explain: "18×13" },
  { id: "mf34-5", cat: "math", grade: 34, q: "21 個小朋友每人 14 顆糖，一共幾顆？", options: ["294", "35", "7", "295"], answer: 0, explain: "21×14" },
  { id: "mf34-6", cat: "math", grade: 34, q: "24 個小朋友每人 15 顆糖，一共幾顆？", options: ["360", "39", "9", "361"], answer: 0, explain: "24×15" },
  { id: "mf34-7", cat: "math", grade: 34, q: "27 個小朋友每人 16 顆糖，一共幾顆？", options: ["432", "43", "11", "433"], answer: 0, explain: "27×16" },
  { id: "mf34-8", cat: "math", grade: 34, q: "30 個小朋友每人 17 顆糖，一共幾顆？", options: ["510", "47", "13", "511"], answer: 0, explain: "30×17" },
  { id: "mf34-9", cat: "math", grade: 34, q: "33 個小朋友每人 18 顆糖，一共幾顆？", options: ["594", "51", "15", "595"], answer: 0, explain: "33×18" },
  { id: "mf34-10", cat: "math", grade: 34, q: "36 個小朋友每人 19 顆糖，一共幾顆？", options: ["684", "55", "17", "685"], answer: 0, explain: "36×19" },
  { id: "mf34-11", cat: "math", grade: 34, q: "39 個小朋友每人 20 顆糖，一共幾顆？", options: ["780", "59", "19", "781"], answer: 0, explain: "39×20" },
  { id: "mf56-0", cat: "math", grade: 56, q: "11 個小朋友每人 14 顆糖，一共幾顆？", options: ["154", "25", "3", "155"], answer: 0, explain: "11×14" },
  { id: "mf56-1", cat: "math", grade: 56, q: "15 個小朋友每人 15 顆糖，一共幾顆？", options: ["225", "30", "17", "226"], answer: 0, explain: "15×15" },
  { id: "mf56-2", cat: "math", grade: 56, q: "19 個小朋友每人 16 顆糖，一共幾顆？", options: ["304", "35", "3", "305"], answer: 0, explain: "19×16" },
  { id: "mf56-3", cat: "math", grade: 56, q: "23 個小朋友每人 17 顆糖，一共幾顆？", options: ["391", "40", "6", "392"], answer: 0, explain: "23×17" },
  { id: "mf56-4", cat: "math", grade: 56, q: "27 個小朋友每人 18 顆糖，一共幾顆？", options: ["486", "45", "9", "487"], answer: 0, explain: "27×18" },
  { id: "mf56-5", cat: "math", grade: 56, q: "31 個小朋友每人 19 顆糖，一共幾顆？", options: ["589", "50", "12", "590"], answer: 0, explain: "31×19" },
  { id: "mf56-6", cat: "math", grade: 56, q: "35 個小朋友每人 20 顆糖，一共幾顆？", options: ["700", "55", "15", "701"], answer: 0, explain: "35×20" },
  { id: "mf56-7", cat: "math", grade: 56, q: "39 個小朋友每人 21 顆糖，一共幾顆？", options: ["819", "60", "18", "820"], answer: 0, explain: "39×21" },
  { id: "mf56-8", cat: "math", grade: 56, q: "43 個小朋友每人 22 顆糖，一共幾顆？", options: ["946", "65", "21", "947"], answer: 0, explain: "43×22" },
  { id: "mf56-9", cat: "math", grade: 56, q: "47 個小朋友每人 23 顆糖，一共幾顆？", options: ["1081", "70", "24", "1082"], answer: 0, explain: "47×23" },
  { id: "mf56-10", cat: "math", grade: 56, q: "51 個小朋友每人 24 顆糖，一共幾顆？", options: ["1224", "75", "27", "1225"], answer: 0, explain: "51×24" },
  { id: "mf56-11", cat: "math", grade: 56, q: "55 個小朋友每人 25 顆糖，一共幾顆？", options: ["1375", "80", "30", "1376"], answer: 0, explain: "55×25" },
  { id: "lo12-1", cat: "lang", grade: 12, q: "哪一個跟其他三個不同類？", options: ["香蕉", "汽車", "火車", "飛機"], answer: 0, explain: "香蕉不是交通工具" },
  { id: "lo12-2", cat: "lang", grade: 12, q: "哪一個跟其他三個不同類？", options: ["跑", "紅", "黃", "藍"], answer: 0, explain: "跑不是顏色" },
  { id: "lo12-3", cat: "lang", grade: 12, q: "哪一個跟其他三個不同類？", options: ["門", "春", "夏", "秋"], answer: 0, explain: "門不是季節" },
  { id: "lo23-1", cat: "lang", grade: 23, q: "哪一個跟其他三個不同類？", options: ["黑板", "鋼琴", "吉他", "笛子"], answer: 0, explain: "黑板不是樂器" },
  { id: "lo23-2", cat: "lang", grade: 23, q: "哪一個跟其他三個不同類？", options: ["快樂", "圓", "方", "三角"], answer: 0, explain: "快樂不是形狀" },
  { id: "lo23-3", cat: "lang", grade: 23, q: "哪一個跟其他三個不同類？", options: ["醫院", "醫生", "護理師", "司機"], answer: 0, explain: "醫院是地方不是職業" },
  { id: "lo34-1", cat: "lang", grade: 34, q: "哪一個跟其他三個不同類？", options: ["橡皮擦", "小說", "詩", "劇本"], answer: 0, explain: "橡皮擦不是文類" },
  { id: "lo34-2", cat: "lang", grade: 34, q: "哪一個跟其他三個不同類？", options: ["跑步", "蒸發", "凝固", "融化"], answer: 0, explain: "跑步不是物態變化" },
  { id: "lo34-3", cat: "lang", grade: 34, q: "哪一個跟其他三個不同類？", options: ["鉛筆盒", "原因", "結果", "過程"], answer: 0, explain: "鉛筆盒不是事件結構" },
  { id: "lo56-1", cat: "lang", grade: 56, q: "哪一個跟其他三個不同類？", options: ["書包帶", "假設", "證據", "結論"], answer: 0, explain: "書包帶不是論證要素" },
  { id: "lo56-2", cat: "lang", grade: 56, q: "哪一個跟其他三個不同類？", options: ["唱歌", "平行", "垂直", "相交"], answer: 0, explain: "唱歌不是直線關係" },
  { id: "lo56-3", cat: "lang", grade: 56, q: "哪一個跟其他三個不同類？", options: ["操場", "主詞", "動詞", "受詞"], answer: 0, explain: "操場不是句子成分" },
  { id: "mr12-1", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 3、8、1", options: ["1、8、3", "3、8、1", "8、1、3", "8、3、2"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-1", cat: "mem", grade: 12, q: "記住：3、8、1。從左邊數來第 3 個是哪一個？", options: ["1", "3", "11", "28"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-2", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 6、2、9", options: ["9、2、6", "6、2、9", "2、9、6", "2、6、10"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-2", cat: "mem", grade: 12, q: "記住：6、2、9。從左邊數來第 3 個是哪一個？", options: ["9", "6", "19", "22"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-3", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 4、4、5", options: ["5、4、4", "4、4、5", "4、5、4", "4、4、6"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-3", cat: "mem", grade: 12, q: "記住：4、4、5。從左邊數來第 3 個是哪一個？", options: ["5", "4", "15", "24"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-4", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 7、0、2", options: ["2、0、7", "7、0、2", "0、2、7", "0、7、3"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-4", cat: "mem", grade: 12, q: "記住：7、0、2。從左邊數來第 3 個是哪一個？", options: ["2", "7", "12", "20"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-5", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 1、9、6", options: ["6、9、1", "1、9、6", "9、6、1", "9、1、7"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-5", cat: "mem", grade: 12, q: "記住：1、9、6。從左邊數來第 3 個是哪一個？", options: ["6", "1", "16", "29"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-6", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 8、3、3", options: ["3、3、8", "8、3、3", "3、8、4", "3、3、0"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-6", cat: "mem", grade: 12, q: "記住：8、3、3。從左邊數來第 3 個是哪一個？", options: ["3", "8", "13", "23"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-7", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 2、5、7", options: ["7、5、2", "2、5、7", "5、7、2", "5、2、8"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-7", cat: "mem", grade: 12, q: "記住：2、5、7。從左邊數來第 3 個是哪一個？", options: ["7", "2", "17", "25"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-8", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 9、1、4", options: ["4、1、9", "9、1、4", "1、4、9", "1、9、5"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-8", cat: "mem", grade: 12, q: "記住：9、1、4。從左邊數來第 3 個是哪一個？", options: ["4", "9", "14", "21"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-9", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 0、6、8", options: ["8、6、0", "0、6、8", "6、8、0", "6、0、9"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-9", cat: "mem", grade: 12, q: "記住：0、6、8。從左邊數來第 3 個是哪一個？", options: ["8", "0", "18", "26"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr12-10", cat: "mem", grade: 12, q: "記住下面這串數字，從最後一個往回唸，順序是？ 5、5、2", options: ["2、5、5", "5、5、2", "5、2、5", "5、5、3"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp12-10", cat: "mem", grade: 12, q: "記住：5、5、2。從左邊數來第 3 個是哪一個？", options: ["2", "5", "12", "25"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-1", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 3、1、8、4", options: ["4、8、1、3", "3、1、8、4", "1、8、4、3", "8、1、3、5"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-1", cat: "mem", grade: 23, q: "記住：3、1、8、4。從左邊數來第 3 個是哪一個？", options: ["8", "3", "14", "21"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-2", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 9、2、2、7", options: ["7、2、2、9", "9、2、2、7", "2、2、7、9", "2、2、9、8"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-2", cat: "mem", grade: 23, q: "記住：9、2、2、7。從左邊數來第 3 個是哪一個？", options: ["2", "9", "17", "22"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-3", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 5、0、6、1", options: ["1、6、0、5", "5、0、6、1", "0、6、1、5", "6、0、5、2"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-3", cat: "mem", grade: 23, q: "記住：5、0、6、1。從左邊數來第 3 個是哪一個？", options: ["6", "5", "11", "20"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-4", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 8、8、3、4", options: ["4、3、8、8", "8、8、3、4", "8、3、4、8", "3、8、8、5"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-4", cat: "mem", grade: 23, q: "記住：8、8、3、4。從左邊數來第 3 個是哪一個？", options: ["3", "8", "14", "28"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-5", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 1、7、9、0", options: ["0、9、7、1", "1、7、9、0", "7、9、0、1", "9、7、1、1"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-5", cat: "mem", grade: 23, q: "記住：1、7、9、0。從左邊數來第 3 個是哪一個？", options: ["9", "1", "10", "27"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-6", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 4、6、2、5", options: ["5、2、6、4", "4、6、2、5", "6、2、5、4", "2、6、4、6"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-6", cat: "mem", grade: 23, q: "記住：4、6、2、5。從左邊數來第 3 個是哪一個？", options: ["2", "4", "15", "26"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-7", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 2、9、1、8", options: ["8、1、9、2", "2、9、1、8", "9、1、8、2", "1、9、2、9"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-7", cat: "mem", grade: 23, q: "記住：2、9、1、8。從左邊數來第 3 個是哪一個？", options: ["1", "2", "18", "29"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-8", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 7、3、5、5", options: ["5、5、3、7", "7、3、5、5", "3、5、5、7", "5、3、7、6"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-8", cat: "mem", grade: 23, q: "記住：7、3、5、5。從左邊數來第 3 個是哪一個？", options: ["5", "7", "15", "23"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-9", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 6、4、0、9", options: ["9、0、4、6", "6、4、0、9", "4、0、9、6", "0、4、6、10"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-9", cat: "mem", grade: 23, q: "記住：6、4、0、9。從左邊數來第 3 個是哪一個？", options: ["0", "6", "19", "24"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr23-10", cat: "mem", grade: 23, q: "記住下面這串數字，從最後一個往回唸，順序是？ 1、1、2、8", options: ["8、2、1、1", "1、1、2、8", "1、2、8、1", "2、1、1、9"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp23-10", cat: "mem", grade: 23, q: "記住：1、1、2、8。從左邊數來第 3 個是哪一個？", options: ["2", "1", "18", "21"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-1", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 4、8、1、9、3", options: ["3、9、1、8、4", "4、8、1、9、3", "8、1、9、3、4", "9、1、8、4、4"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-1", cat: "mem", grade: 34, q: "記住：4、8、1、9、3。從左邊數來第 3 個是哪一個？", options: ["1", "4", "13", "28"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-2", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 2、7、7、0、5", options: ["5、0、7、7、2", "2、7、7、0、5", "7、7、0、5、2", "0、7、7、2、6"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-2", cat: "mem", grade: 34, q: "記住：2、7、7、0、5。從左邊數來第 3 個是哪一個？", options: ["7", "2", "15", "27"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-3", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 9、1、6、4、2", options: ["2、4、6、1、9", "9、1、6、4、2", "1、6、4、2、9", "4、6、1、9、3"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-3", cat: "mem", grade: 34, q: "記住：9、1、6、4、2。從左邊數來第 3 個是哪一個？", options: ["6", "9", "12", "21"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-4", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 3、3、8、1、7", options: ["7、1、8、3、3", "3、3、8、1、7", "3、8、1、7、3", "1、8、3、3、8"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-4", cat: "mem", grade: 34, q: "記住：3、3、8、1、7。從左邊數來第 3 個是哪一個？", options: ["8", "3", "17", "23"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-5", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 5、9、2、6、6", options: ["6、6、2、9、5", "5、9、2、6、6", "9、2、6、6、5", "6、2、9、5、7"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-5", cat: "mem", grade: 34, q: "記住：5、9、2、6、6。從左邊數來第 3 個是哪一個？", options: ["2", "5", "16", "29"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-6", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 8、0、4、1、9", options: ["9、1、4、0、8", "8、0、4、1、9", "0、4、1、9、8", "1、4、0、8、10"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-6", cat: "mem", grade: 34, q: "記住：8、0、4、1、9。從左邊數來第 3 個是哪一個？", options: ["4", "8", "19", "20"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-7", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 1、5、9、3、2", options: ["2、3、9、5、1", "1、5、9、3、2", "5、9、3、2、1", "3、9、5、1、3"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-7", cat: "mem", grade: 34, q: "記住：1、5、9、3、2。從左邊數來第 3 個是哪一個？", options: ["9", "1", "12", "25"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-8", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 7、2、8、8、4", options: ["4、8、8、2、7", "7、2、8、8、4", "2、8、8、4、7", "8、8、2、7、5"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-8", cat: "mem", grade: 34, q: "記住：7、2、8、8、4。從左邊數來第 3 個是哪一個？", options: ["8", "7", "14", "22"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-9", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 6、1、0、5、3", options: ["3、5、0、1、6", "6、1、0、5、3", "1、0、5、3、6", "5、0、1、6、4"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-9", cat: "mem", grade: 34, q: "記住：6、1、0、5、3。從左邊數來第 3 個是哪一個？", options: ["0", "6", "13", "21"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr34-10", cat: "mem", grade: 34, q: "記住下面這串數字，從最後一個往回唸，順序是？ 9、4、4、7、1", options: ["1、7、4、4、9", "9、4、4、7、1", "4、4、7、1、9", "7、4、4、9、2"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp34-10", cat: "mem", grade: 34, q: "記住：9、4、4、7、1。從左邊數來第 3 個是哪一個？", options: ["4", "9", "11", "24"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-1", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 5、2、9、1、8、3", options: ["3、8、1、9、2、5", "5、2、9、1、8、3", "2、9、1、8、3、5", "8、1、9、2、5、4"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-1", cat: "mem", grade: 56, q: "記住：5、2、9、1、8、3。從左邊數來第 3 個是哪一個？", options: ["9", "5", "13", "22"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-2", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 7、0、4、4、6、1", options: ["1、6、4、4、0、7", "7、0、4、4、6、1", "0、4、4、6、1、7", "6、4、4、0、7、2"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-2", cat: "mem", grade: 56, q: "記住：7、0、4、4、6、1。從左邊數來第 3 個是哪一個？", options: ["4", "7", "11", "20"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-3", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 1、8、3、9、2、7", options: ["7、2、9、3、8、1", "1、8、3、9、2、7", "8、3、9、2、7、1", "2、9、3、8、1、8"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-3", cat: "mem", grade: 56, q: "記住：1、8、3、9、2、7。從左邊數來第 3 個是哪一個？", options: ["3", "1", "17", "28"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-4", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 6、6、1、5、0、8", options: ["8、0、5、1、6、6", "6、6、1、5、0、8", "6、1、5、0、8、6", "0、5、1、6、6、9"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-4", cat: "mem", grade: 56, q: "記住：6、6、1、5、0、8。從左邊數來第 3 個是哪一個？", options: ["1", "6", "18", "26"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-5", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 9、3、7、2、4、4", options: ["4、4、2、7、3、9", "9、3、7、2、4、4", "3、7、2、4、4、9", "4、2、7、3、9、5"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-5", cat: "mem", grade: 56, q: "記住：9、3、7、2、4、4。從左邊數來第 3 個是哪一個？", options: ["7", "9", "14", "23"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-6", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 2、5、8、1、9、0", options: ["0、9、1、8、5、2", "2、5、8、1、9、0", "5、8、1、9、0、2", "9、1、8、5、2、1"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-6", cat: "mem", grade: 56, q: "記住：2、5、8、1、9、0。從左邊數來第 3 個是哪一個？", options: ["8", "2", "10", "25"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-7", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 4、9、0、6、3、7", options: ["7、3、6、0、9、4", "4、9、0、6、3、7", "9、0、6、3、7、4", "3、6、0、9、4、8"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-7", cat: "mem", grade: 56, q: "記住：4、9、0、6、3、7。從左邊數來第 3 個是哪一個？", options: ["0", "4", "17", "29"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-8", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 8、1、1、7、5、2", options: ["2、5、7、1、1、8", "8、1、1、7、5、2", "1、1、7、5、2、8", "5、7、1、1、8、3"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-8", cat: "mem", grade: 56, q: "記住：8、1、1、7、5、2。從左邊數來第 3 個是哪一個？", options: ["1", "8", "12", "21"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-9", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 3、6、9、4、8、1", options: ["1、8、4、9、6、3", "3、6、9、4、8、1", "6、9、4、8、1、3", "8、4、9、6、3、2"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-9", cat: "mem", grade: 56, q: "記住：3、6、9、4、8、1。從左邊數來第 3 個是哪一個？", options: ["9", "3", "11", "26"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "mr56-10", cat: "mem", grade: 56, q: "記住下面這串數字，從最後一個往回唸，順序是？ 0、7、2、5、5、9", options: ["9、5、5、2、7、0", "0、7、2、5、5、9", "7、2、5、5、9、0", "5、5、2、7、0、10"], answer: 0, explain: "倒過來＝從右邊唸到左邊。" },
  { id: "mp56-10", cat: "mem", grade: 56, q: "記住：0、7、2、5、5、9。從左邊數來第 3 個是哪一個？", options: ["2", "0", "19", "27"], answer: 0, explain: "從左邊第一個開始數。" },
  { id: "fp12-0", cat: "fig", grade: 12, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-1", cat: "fig", grade: 12, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-2", cat: "fig", grade: 12, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-3", cat: "fig", grade: 12, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-4", cat: "fig", grade: 12, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-5", cat: "fig", grade: 12, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-6", cat: "fig", grade: 12, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-7", cat: "fig", grade: 12, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-8", cat: "fig", grade: 12, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-9", cat: "fig", grade: 12, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-10", cat: "fig", grade: 12, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-11", cat: "fig", grade: 12, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-12", cat: "fig", grade: 12, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-13", cat: "fig", grade: 12, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-14", cat: "fig", grade: 12, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-15", cat: "fig", grade: 12, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-16", cat: "fig", grade: 12, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-17", cat: "fig", grade: 12, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-18", cat: "fig", grade: 12, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-19", cat: "fig", grade: 12, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-20", cat: "fig", grade: 12, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-21", cat: "fig", grade: 12, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-22", cat: "fig", grade: 12, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp12-23", cat: "fig", grade: 12, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-0", cat: "fig", grade: 23, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-1", cat: "fig", grade: 23, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-2", cat: "fig", grade: 23, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-3", cat: "fig", grade: 23, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-4", cat: "fig", grade: 23, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-5", cat: "fig", grade: 23, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-6", cat: "fig", grade: 23, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-7", cat: "fig", grade: 23, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-8", cat: "fig", grade: 23, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-9", cat: "fig", grade: 23, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-10", cat: "fig", grade: 23, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-11", cat: "fig", grade: 23, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-12", cat: "fig", grade: 23, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-13", cat: "fig", grade: 23, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-14", cat: "fig", grade: 23, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-15", cat: "fig", grade: 23, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-16", cat: "fig", grade: 23, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-17", cat: "fig", grade: 23, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-18", cat: "fig", grade: 23, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-19", cat: "fig", grade: 23, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-20", cat: "fig", grade: 23, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-21", cat: "fig", grade: 23, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-22", cat: "fig", grade: 23, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp23-23", cat: "fig", grade: 23, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fp34-0", cat: "fig", grade: 34, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-0", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-1", cat: "fig", grade: 34, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-1", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-2", cat: "fig", grade: 34, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-2", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-3", cat: "fig", grade: 34, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-3", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-4", cat: "fig", grade: 34, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-4", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-5", cat: "fig", grade: 34, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-5", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-6", cat: "fig", grade: 34, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-6", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-7", cat: "fig", grade: 34, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-7", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-8", cat: "fig", grade: 34, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-8", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-9", cat: "fig", grade: 34, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-9", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-10", cat: "fig", grade: 34, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-10", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-11", cat: "fig", grade: 34, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-11", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-12", cat: "fig", grade: 34, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-12", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-13", cat: "fig", grade: 34, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-13", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-14", cat: "fig", grade: 34, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-14", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-15", cat: "fig", grade: 34, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-15", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-16", cat: "fig", grade: 34, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-16", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-17", cat: "fig", grade: 34, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-17", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-18", cat: "fig", grade: 34, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-18", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-19", cat: "fig", grade: 34, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-19", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-20", cat: "fig", grade: 34, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-20", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-21", cat: "fig", grade: 34, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-21", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-22", cat: "fig", grade: 34, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-22", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-23", cat: "fig", grade: 34, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-23", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-24", cat: "fig", grade: 34, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-24", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-25", cat: "fig", grade: 34, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-25", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-26", cat: "fig", grade: 34, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-26", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp34-27", cat: "fig", grade: 34, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr34-27", cat: "fig", grade: 34, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-0", cat: "fig", grade: 56, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-0", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-1", cat: "fig", grade: 56, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-1", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-2", cat: "fig", grade: 56, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-2", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-3", cat: "fig", grade: 56, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-3", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-4", cat: "fig", grade: 56, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-4", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-5", cat: "fig", grade: 56, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-5", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-6", cat: "fig", grade: 56, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-6", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-7", cat: "fig", grade: 56, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-7", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-8", cat: "fig", grade: 56, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-8", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-9", cat: "fig", grade: 56, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-9", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-10", cat: "fig", grade: 56, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-10", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-11", cat: "fig", grade: 56, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-11", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-12", cat: "fig", grade: 56, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-12", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-13", cat: "fig", grade: 56, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-13", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-14", cat: "fig", grade: 56, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-14", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-15", cat: "fig", grade: 56, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-15", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-16", cat: "fig", grade: 56, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-16", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-17", cat: "fig", grade: 56, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-17", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-18", cat: "fig", grade: 56, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-18", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-19", cat: "fig", grade: 56, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-19", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-20", cat: "fig", grade: 56, q: "找出下一個：○ ★ ○ ★ ○ ？", options: ["★", "○", "◆", "△"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-20", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-21", cat: "fig", grade: 56, q: "找出下一個：△ ▲ △ ▲ △ ？", options: ["▲", "△", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-21", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-22", cat: "fig", grade: 56, q: "找出下一個：□ ● □ ● □ ？", options: ["●", "□", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-22", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-23", cat: "fig", grade: 56, q: "找出下一個：★ ■ ★ ■ ★ ？", options: ["■", "★", "◆", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-23", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-24", cat: "fig", grade: 56, q: "找出下一個：▲ ◆ ▲ ◆ ▲ ？", options: ["◆", "▲", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-24", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-25", cat: "fig", grade: 56, q: "找出下一個：● ○ ● ○ ● ？", options: ["○", "●", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-25", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「中」。下一個是哪一格？", options: ["右", "左", "中", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-26", cat: "fig", grade: 56, q: "找出下一個：■ △ ■ △ ■ ？", options: ["△", "■", "★", "◆"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-26", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「右」。下一個是哪一格？", options: ["左", "中", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "fp56-27", cat: "fig", grade: 56, q: "找出下一個：◆ □ ◆ □ ◆ ？", options: ["□", "◆", "★", "○"], answer: 0, explain: "兩種圖形輪流出現，下一個接第二種。" },
  { id: "fr56-27", cat: "fig", grade: 56, q: "黑點照這個順序走：左→中→右→左→中…（走完右就回到左，一直重複）。現在在「左」。下一個是哪一格？", options: ["中", "左", "右", "三格都有"], answer: 0, explain: "左→中→右→左，這樣循環。" },
  { id: "la12-1", cat: "lang", grade: 12, q: "「熱」的相反最接近？", options: ["冷", "快", "火", "高"], answer: 0, explain: "反義" },
  { id: "la12-2", cat: "lang", grade: 12, q: "「開」的相反最接近？", options: ["關", "門", "走", "放"], answer: 0, explain: "反義" },
  { id: "la12-3", cat: "lang", grade: 12, q: "「早」的相反最接近？", options: ["晚", "中", "午", "年"], answer: 0, explain: "反義" },
  { id: "la23-4", cat: "lang", grade: 23, q: "「安全」的相反最接近？", options: ["危險", "保護", "小心", "平安"], answer: 0, explain: "反義" },
  { id: "la23-5", cat: "lang", grade: 23, q: "「誠實」的相反最接近？", options: ["欺騙", "認真", "客氣", "坦白"], answer: 0, explain: "反義" },
  { id: "la23-6", cat: "lang", grade: 23, q: "「成功」的相反最接近？", options: ["失敗", "努力", "高興", "完成"], answer: 0, explain: "反義" },
  { id: "la34-7", cat: "lang", grade: 34, q: "「暫時」的相反最接近？", options: ["永久", "很快", "有時", "今天"], answer: 0, explain: "反義" },
  { id: "la34-8", cat: "lang", grade: 34, q: "「稀疏」的相反最接近？", options: ["密集", "很多", "很少", "剛好"], answer: 0, explain: "反義" },
  { id: "la34-9", cat: "lang", grade: 34, q: "「樂觀」的相反最接近？", options: ["悲觀", "生氣", "睡覺", "走路"], answer: 0, explain: "反義" },
  { id: "la56-10", cat: "lang", grade: 56, q: "「抽象」的相反最接近？", options: ["具體", "漂亮", "快速", "巨大"], answer: 0, explain: "反義" },
  { id: "la56-11", cat: "lang", grade: 56, q: "「主觀」的相反最接近？", options: ["客觀", "正確", "錯誤", "漂亮"], answer: 0, explain: "反義" },
  { id: "la56-12", cat: "lang", grade: 56, q: "「擴張」的相反最接近？", options: ["收縮", "移動", "停止", "旋轉"], answer: 0, explain: "反義" },
  { id: "ln12-1", cat: "lang", grade: 12, q: "鳥：天空＝魚：？", options: ["水裡", "樹上", "路上", "雲上"], answer: 0, explain: "類比" },
  { id: "ln12-2", cat: "lang", grade: 12, q: "手：手套＝腳：？", options: ["鞋子", "帽子", "杯子", "門"], answer: 0, explain: "類比" },
  { id: "ln23-3", cat: "lang", grade: 23, q: "書：讀＝歌：？", options: ["唱", "跑", "睡", "寫字只寫"], answer: 0, explain: "類比" },
  { id: "ln23-4", cat: "lang", grade: 23, q: "白天：太陽＝夜晚：？", options: ["月亮", "早餐", "書包", "教室"], answer: 0, explain: "類比" },
  { id: "ln34-5", cat: "lang", grade: 34, q: "作者：書＝作曲家：？", options: ["歌曲", "讀者", "紙", "鉛筆"], answer: 0, explain: "類比" },
  { id: "ln34-6", cat: "lang", grade: 34, q: "種子：植物＝蛋：？", options: ["小雞", "石頭", "水", "桌子"], answer: 0, explain: "類比" },
  { id: "ln56-7", cat: "lang", grade: 56, q: "因：果＝問題：？", options: ["解答", "天氣", "顏色", "星期"], answer: 0, explain: "類比" },
  { id: "ln56-8", cat: "lang", grade: 56, q: "地圖：道路＝樂譜：？", options: ["旋律", "鞋子", "窗戶", "橡皮"], answer: 0, explain: "類比" },
  { id: "lx12-1", cat: "lang", grade: 12, q: "「新」的相反最接近？", options: ["舊", "好", "多", "快"], answer: 0, explain: "反義" },
  { id: "lx12-2", cat: "lang", grade: 12, q: "「長」的相反最接近？", options: ["短", "高", "遠", "大"], answer: 0, explain: "反義" },
  { id: "lx12-3", cat: "lang", grade: 12, q: "「前」的相反最接近？", options: ["後", "上", "裡", "中"], answer: 0, explain: "反義" },
  { id: "lx12-4", cat: "lang", grade: 12, q: "「多」的相反最接近？", options: ["少", "大", "好", "快"], answer: 0, explain: "反義" },
  { id: "lx12-5", cat: "lang", grade: 12, q: "「亮」的相反最接近？", options: ["暗", "紅", "圓", "遠"], answer: 0, explain: "反義" },
  { id: "lx23-6", cat: "lang", grade: 23, q: "「接受」的相反最接近？", options: ["拒絕", "喜歡", "幫忙", "看見"], answer: 0, explain: "反義" },
  { id: "lx23-7", cat: "lang", grade: 23, q: "「簡單」的相反最接近？", options: ["困難", "快樂", "漂亮", "安靜"], answer: 0, explain: "反義" },
  { id: "lx23-8", cat: "lang", grade: 23, q: "「出現」的相反最接近？", options: ["消失", "走路", "吃飯", "睡覺"], answer: 0, explain: "反義" },
  { id: "lx23-9", cat: "lang", grade: 23, q: "「增加」的相反最接近？", options: ["減少", "等於", "看見", "打開"], answer: 0, explain: "反義" },
  { id: "lx23-10", cat: "lang", grade: 23, q: "「朋友」的相反最接近？", options: ["敵人", "同學", "老師", "家人"], answer: 0, explain: "反義" },
  { id: "lx34-11", cat: "lang", grade: 34, q: "「清楚」的相反最接近？", options: ["模糊", "快速", "美麗", "安靜"], answer: 0, explain: "反義" },
  { id: "lx34-12", cat: "lang", grade: 34, q: "「包含」的相反最接近？", options: ["排除", "計算", "書寫", "跑步"], answer: 0, explain: "反義" },
  { id: "lx34-13", cat: "lang", grade: 34, q: "「贊成」的相反最接近？", options: ["反對", "討論", "休息", "開始"], answer: 0, explain: "反義" },
  { id: "lx34-14", cat: "lang", grade: 34, q: "「天然」的相反最接近？", options: ["人工", "漂亮", "巨大", "微小"], answer: 0, explain: "反義" },
  { id: "lx34-15", cat: "lang", grade: 34, q: "「穩定」的相反最接近？", options: ["不穩定", "高興", "彩色", "圓形"], answer: 0, explain: "反義" },
  { id: "lx56-16", cat: "lang", grade: 56, q: "「局部」的相反最接近？", options: ["全部", "一半", "外面", "上面"], answer: 0, explain: "反義" },
  { id: "lx56-17", cat: "lang", grade: 56, q: "「必然」的相反最接近？", options: ["偶然", "常常", "永遠", "昨天"], answer: 0, explain: "反義" },
  { id: "lx56-18", cat: "lang", grade: 56, q: "「分析」的相反最接近？", options: ["綜合", "背誦", "睡覺", "畫畫"], answer: 0, explain: "反義" },
  { id: "lx56-19", cat: "lang", grade: 56, q: "「主動」的相反最接近？", options: ["被動", "快樂", "快速", "安靜"], answer: 0, explain: "反義" },
  { id: "lx56-20", cat: "lang", grade: 56, q: "「相對」的相反最接近？", options: ["絕對", "大約", "剛好", "很多"], answer: 0, explain: "反義" },
];

export const GIFTED_CAT_LABEL = { fig: "圖形空間", lang: "語文理解", math: "數量推理", mem: "工作記憶" };
export const GIFTED_GRADE_LABEL = { 12: "1～2年級", 23: "2～3年級", 34: "3～4年級", 56: "5～6年級" };
