
var Rapfi = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName ||= __filename;
  return (
function(moduleArg = {}) {
  var moduleRtn;

var g=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node;g.kb||(g.kb=0);g.kb++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(l,p,q,z){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(l,function(r,u){r?z(r):q(u.buffer)});else{var t=new XMLHttpRequest;t.open("GET",l,!0);t.responseType="arraybuffer";t.onprogress=function(r){var u=p;r.total&&(u=r.total);if(r.loaded){t.Ta?
g.cb[l].loaded=r.loaded:(t.Ta=!0,g.cb||(g.cb={}),g.cb[l]={loaded:r.loaded,total:u});var F=u=r=0,M;for(M in g.cb){var S=g.cb[M];r+=S.total;u+=S.loaded;F++}r=Math.ceil(r*g.kb/F);g.setStatus?.(`Downloading data... (${u}/${r})`)}else g.cb||g.setStatus?.("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+l);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)q(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}}
function d(l){console.error("package error:",l)}function e(l){function p(r,u,F){this.start=r;this.end=u;this.audio=F}function q(r){if(!r)throw"Loading data file failed."+Error().stack;if(r.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;r=new Uint8Array(r);p.prototype.gb=r;r=b.files;for(var u=0;u<r.length;++u)p.prototype.Ta[r[u].filename].onload();l.removeRunDependency("datafile_rapfi-single.data")}p.prototype={Ta:{},open:function(r,u){this.name=u;this.Ta[u]=
this;l.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.fb(this.gb.subarray(this.start,this.end))},fb:function(r){l.FS_createDataFile(this.name,null,r,!0,!0,!0);l.removeRunDependency(`fp ${this.name}`);this.Ta[this.name]=null}};for(var z=b.files,t=0;t<z.length;++t)(new p(z[t].start,z[t].end,z[t].audio||0)).open("GET",z[t].filename);l.addRunDependency("datafile_rapfi-single.data");l.zb||(l.zb={});l.zb["rapfi-single.data"]={Rb:!1};n?(q(n),n=null):k=q}"object"===typeof window?
window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,m("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var f=g.locateFile?g.locateFile("rapfi-single.data",""):"rapfi-single.data",h=b.remote_package_size,k=null,n=g.getPreloadedPackage?g.getPreloadedPackage(f,h):null;n||c(f,h,function(l){k?(k(l),k=null):n=l},d);g.calledRun?e(g):(g.preRun||(g.preRun=[]),g.preRun.push(e))}({files:[{filename:"/classical210901.toml",start:0,end:5921},{filename:"/classical220723.toml",start:5921,end:11842},{filename:"/model210901.bin",start:11842,end:35046},{filename:"/model220723.bin",start:35046,end:94776}],remote_package_size:94776})})();
g.sendCommand=g.sendCommand||null;g.terminate=g.terminate||null;g.onReceiveStdout=g.onReceiveStdout||(a=>console.log(a));g.onReceiveStderr=g.onReceiveStderr||(a=>console.error(a));g.onExit=g.onExit||(a=>console.log("exited with code "+a));g.noExitRuntime=!0;g.preRun||(g.preRun=[]);
g.preRun.push(function(){let a=[];var b="",c=0;let d="",e="";const f=g.onReceiveStdout,h=g.onReceiveStderr;ha(function(){return c<b.length?b.charCodeAt(c++):0<a.length?(b=a.shift(),c=0,b.charCodeAt(c++)):null},function(n){n&&10!=n?d+=String.fromCharCode(n):(f(d),d="")},function(n){n&&10!=n?e+=String.fromCharCode(n):(h(e),e="")});const k=g.cwrap("gomocupLoopOnce","number",[]);g.sendCommand=function(n){a.push(n+"\n");k()};g.terminate=function(){g._emscripten_force_exit(0)}});
var ia=Object.assign({},g),ja=[],ka="./this.program",la=(a,b)=>{throw b;},v="",ma,na;
if(fa){var fs=require("fs"),oa=require("path");v=__dirname+"/";na=a=>{a=pa(a)?new URL(a):oa.normalize(a);return fs.readFileSync(a)};ma=a=>{a=pa(a)?new URL(a):oa.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!g.thisProgram&&1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);la=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ea?v=self.location.href:"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src),
_scriptName&&(v=_scriptName),v.startsWith("blob:")?v="":v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(na=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ma=a=>pa(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var qa=g.print||console.log.bind(console),m=g.printErr||console.error.bind(console);Object.assign(g,ia);ia=null;g.arguments&&(ja=g.arguments);g.thisProgram&&(ka=g.thisProgram);g.quit&&(la=g.quit);var ra;g.wasmBinary&&(ra=g.wasmBinary);var sa,ta=!1,w,x,ua,y,A;
function va(){var a=sa.buffer;g.HEAP8=w=new Int8Array(a);g.HEAP16=ua=new Int16Array(a);g.HEAPU8=x=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAP32=y=new Int32Array(a);g.HEAPU32=A=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}g.wasmMemory?sa=g.wasmMemory:sa=new WebAssembly.Memory({initial:(g.INITIAL_MEMORY||16777216)/65536,maximum:32768});va();var wa=[],xa=[],ya=[],za=[],Aa=[];function Ba(){var a=g.preRun.shift();wa.unshift(a)}var Ca=0,Da=null,Ea=null;
function Fa(){Ca++;g.monitorRunDependencies?.(Ca)}function Ga(){Ca--;g.monitorRunDependencies?.(Ca);if(0==Ca&&(null!==Da&&(clearInterval(Da),Da=null),Ea)){var a=Ea;Ea=null;a()}}function Ha(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);ta=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ia=a=>a.startsWith("data:application/octet-stream;base64,"),pa=a=>a.startsWith("file://"),Ja;
function Ka(a){if(a==Ja&&ra)return new Uint8Array(ra);if(na)return na(a);throw"both async and sync fetching of the wasm failed";}function La(a){return ra?Promise.resolve().then(()=>Ka(a)):ma(a).then(b=>new Uint8Array(b),()=>Ka(a))}function Ma(a,b,c){return La(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);Ha(d)})}
function Na(a,b){var c=Ja;return ra||"function"!=typeof WebAssembly.instantiateStreaming||Ia(c)||pa(c)||fa||"function"!=typeof fetch?Ma(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Ma(c,a,b)}))}var B,C;function Oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Pa=a=>{for(;0<a.length;)a.shift()(g)},Qa=g.noExitRuntime||!1,Ra=[],Sa=0,D=0;function Ta(a,b,c){A[a.Ua+16>>2]=0;A[a.Ua+4>>2]=b;A[a.Ua+8>>2]=c}class Ua{constructor(a){this.hb=a;this.Ua=a-24}}var Xa=a=>{var b=D;if(!b)return Va(0),0;var c=new Ua(b);A[c.Ua+16>>2]=b;var d=A[c.Ua+4>>2];if(!d)return Va(0),b;for(var e of a){if(0===e||e===d)break;if(Wa(e,d,c.Ua+16))return Va(e),b}Va(d);return b};function E(){var a=y[+Ya>>2];Ya+=4;return a}
var Za=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Za(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},$a=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},ab=a=>{if("/"===
a)return"/";a=G(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},bb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(fa)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}Ha("initRandomDevice")},cb=a=>(cb=bb())(a),db=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Za(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},eb=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var n=h.length-1;0<=n&&""===h[n];n--);return k>n?[]:h.slice(k,n-k+1)}a=db(a).substr(1);b=db(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},fb="undefined"!=
typeof TextDecoder?new TextDecoder:void 0,H=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&fb)return fb.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},gb=[],hb=a=>{for(var b=0,
c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ib=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=
128|h&63}}b[c]=0;return c-e};function jb(a){var b=Array(hb(a)+1);a=ib(a,b,0,b.length);b.length=a;return b}var kb=[];function lb(a,b){kb[a]={input:[],output:[],$a:b};mb(a,nb)}
var nb={open(a){var b=kb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close(a){a.tty.$a.fsync(a.tty)},fsync(a){a.tty.$a.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.$a.vb)throw new I(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.$a.vb(a.tty)}catch(k){throw new I(29);}if(void 0===h&&0===e)throw new I(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.$a.nb)throw new I(60);try{for(var e=0;e<d;e++)a.tty.$a.nb(a.tty,b[c+
e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},ob={vb(){a:{if(!gb.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}gb=jb(a)}a=gb.shift()}return a},nb(a,b){null===b||10===b?(qa(H(a.output,
0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(qa(H(a.output,0)),a.output=[])},Db(){return{Nb:25856,Pb:5,Mb:191,Ob:35387,Lb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Eb(){return 0},Fb(){return[24,80]}},pb={nb(a,b){null===b||10===b?(m(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(m(H(a.output,0)),a.output=[])}};
function qb(a,b){var c=a.Qa?a.Qa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Qa,a.Qa=new Uint8Array(b),0<a.Sa&&a.Qa.set(c.subarray(0,a.Sa),0))}
var J={Za:null,Xa(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.Za||(J.Za={dir:{node:{Ya:J.Pa.Ya,Wa:J.Pa.Wa,lookup:J.Pa.lookup,jb:J.Pa.jb,rename:J.Pa.rename,unlink:J.Pa.unlink,rmdir:J.Pa.rmdir,readdir:J.Pa.readdir,symlink:J.Pa.symlink},stream:{bb:J.Ra.bb}},file:{node:{Ya:J.Pa.Ya,Wa:J.Pa.Wa},stream:{bb:J.Ra.bb,read:J.Ra.read,write:J.Ra.write,sb:J.Ra.sb,mb:J.Ra.mb,yb:J.Ra.yb}},link:{node:{Ya:J.Pa.Ya,Wa:J.Pa.Wa,readlink:J.Pa.readlink},
stream:{}},tb:{node:{Ya:J.Pa.Ya,Wa:J.Pa.Wa},stream:rb}});c=sb(a,b,c,d);K(c.mode)?(c.Pa=J.Za.dir.node,c.Ra=J.Za.dir.stream,c.Qa={}):32768===(c.mode&61440)?(c.Pa=J.Za.file.node,c.Ra=J.Za.file.stream,c.Sa=0,c.Qa=null):40960===(c.mode&61440)?(c.Pa=J.Za.link.node,c.Ra=J.Za.link.stream):8192===(c.mode&61440)&&(c.Pa=J.Za.tb.node,c.Ra=J.Za.tb.stream);c.timestamp=Date.now();a&&(a.Qa[b]=c,a.timestamp=c.timestamp);return c},Sb(a){return a.Qa?a.Qa.subarray?a.Qa.subarray(0,a.Sa):new Uint8Array(a.Qa):new Uint8Array(0)},
Pa:{Ya(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Sa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Bb=4096;b.blocks=Math.ceil(b.size/b.Bb);return b},Wa(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Sa!=b))if(0==
b)a.Qa=null,a.Sa=0;else{var c=a.Qa;a.Qa=new Uint8Array(b);c&&a.Qa.set(c.subarray(0,Math.min(b,a.Sa)));a.Sa=b}},lookup(){throw tb[44];},jb(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){if(K(a.mode)){try{var d=N(b,c)}catch(f){}if(d)for(var e in d.Qa)throw new I(55);}delete a.parent.Qa[a.name];a.parent.timestamp=Date.now();a.name=c;b.Qa[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.Qa[b];a.timestamp=Date.now()},rmdir(a,b){var c=N(a,b),d;for(d in c.Qa)throw new I(55);delete a.Qa[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.Qa))b.push(c);return b},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},Ra:{read(a,b,c,d,e){var f=a.node.Qa;if(e>=a.node.Sa)return 0;a=Math.min(a.node.Sa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===w.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();
if(b.subarray&&(!a.Qa||a.Qa.subarray)){if(f)return a.Qa=b.subarray(c,c+d),a.Sa=d;if(0===a.Sa&&0===e)return a.Qa=b.slice(c,c+d),a.Sa=d;if(e+d<=a.Sa)return a.Qa.set(b.subarray(c,c+d),e),d}qb(a,e+d);if(a.Qa.subarray&&b.subarray)a.Qa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Qa[e+f]=b[c+f];a.Sa=Math.max(a.Sa,e+d);return d},bb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Sa);if(0>b)throw new I(28);return b},sb(a,b,c){qb(a.node,b+c);a.node.Sa=Math.max(a.node.Sa,b+c)},
mb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.Qa;if(e&2||a.buffer!==w.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;Ha();b=void 0;if(!b)throw new I(48);w.set(a,b)}else c=!1,b=a.byteOffset;return{Ua:b,Kb:c}},yb(a,b,c,d){J.Ra.write(a,b,0,d,c,!1);return 0}}},ub=(a,b,c)=>{var d=`al ${a}`;ma(a).then(e=>{b(new Uint8Array(e));d&&Ga(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Fa(d)},vb=g.preloadPlugins||
[],wb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Ta(Browser);var e=!1;vb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},yb=(a,b,c,d,e,f,h,k,n,l)=>{function p(t){function r(u){l?.();k||xb(a,b,u,d,e,n);f?.();Ga(z)}wb(t,q,r,()=>{h?.();Ga(z)})||r(t)}var q=b?db(G(a+"/"+b)):a,z=`cp ${q}`;Fa(z);"string"==typeof c?ub(c,p,h):p(c)},zb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ab=null,Bb={},Cb=[],Db=1,O=null,Eb=!0,I=class{constructor(a){this.name="ErrnoError";this.Va=a}},tb={},Fb=
class{constructor(){this.Ta={};this.node=null}get flags(){return this.Ta.flags}set flags(a){this.Ta.flags=a}get position(){return this.Ta.position}set position(a){this.Ta.position=a}},Gb=class{constructor(a,b,c,d){a||=this;this.parent=a;this.Xa=a.Xa;this.ab=null;this.id=Db++;this.name=b;this.mode=c;this.Pa={};this.Ra={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=
-147}get Hb(){return K(this.mode)}get Gb(){return 8192===(this.mode&61440)}};
function P(a,b={}){a=db(a);if(!a)return{path:"",node:null};b=Object.assign({ub:!0,ob:0},b);if(8<b.ob)throw new I(32);a=a.split("/").filter(h=>!!h);for(var c=Ab,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=N(c,a[e]);d=G(d+"/"+a[e]);c.ab&&(!f||f&&b.ub)&&(c=c.ab.root);if(!f||b.ib)for(f=0;40960===(c.mode&61440);)if(c=Hb(d),d=db($a(d),c),c=P(d,{ob:b.ob+1}).node,40<f++)throw new I(32);}return{path:d,node:c}}
function Ib(a){for(var b;;){if(a===a.parent)return a=a.Xa.xb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function Kb(a){var b=Jb(a.parent.id,a.name);a.eb=O[b];O[b]=a}function Lb(a){var b=Jb(a.parent.id,a.name);if(O[b]===a)O[b]=a.eb;else for(b=O[b];b;){if(b.eb===a){b.eb=a.eb;break}b=b.eb}}
function N(a,b){var c=K(a.mode)?(c=Mb(a,"x"))?c:a.Pa.lookup?0:2:54;if(c)throw new I(c);for(c=O[Jb(a.id,b)];c;c=c.eb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Pa.lookup(a,b)}function sb(a,b,c,d){a=new Gb(a,b,c,d);Kb(a);return a}function K(a){return 16384===(a&61440)}function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Mb(a,b){if(Eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ob(a,b){try{return N(a,b),20}catch(c){}return Mb(a,"wx")}function Pb(a,b,c){try{var d=N(a,b)}catch(e){return e.Va}if(a=Mb(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(d===d.parent||"/"===Ib(d))return 10}else if(K(d.mode))return 31;return 0}function Q(a){a=Cb[a];if(!a)throw new I(8);return a}
function Qb(a,b=-1){a=Object.assign(new Fb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Cb[b])break a;throw new I(33);}a.fd=b;return Cb[b]=a}function Rb(a,b=-1){a=Qb(a,b);a.Ra?.Qb?.(a);return a}var rb={open(a){a.Ra=Bb[a.node.rdev].Ra;a.Ra.open?.(a)},bb(){throw new I(70);}};function mb(a,b){Bb[a]={Ra:b}}
function Sb(a,b){var c="/"===b;if(c&&Ab)throw new I(10);if(!c&&b){var d=P(b,{ub:!1});b=d.path;d=d.node;if(d.ab)throw new I(10);if(!K(d.mode))throw new I(54);}b={type:a,Tb:{},xb:b,Ib:[]};a=a.Xa(b);a.Xa=b;b.root=a;c?Ab=a:d&&(d.ab=b,d.Xa&&d.Xa.Ib.push(b))}function Tb(a,b,c){var d=P(a,{parent:!0}).node;a=ab(a);if(!a||"."===a||".."===a)throw new I(28);var e=Ob(d,a);if(e)throw new I(e);if(!d.Pa.jb)throw new I(63);return d.Pa.jb(d,a,b,c)}function R(a){return Tb(a,16895,0)}
function Ub(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Tb(a,b|8192,c)}function Vb(a,b){if(!db(a))throw new I(44);var c=P(b,{parent:!0}).node;if(!c)throw new I(44);b=ab(b);var d=Ob(c,b);if(d)throw new I(d);if(!c.Pa.symlink)throw new I(63);c.Pa.symlink(c,b,a)}function Wb(a){var b=P(a,{parent:!0}).node;a=ab(a);var c=N(b,a),d=Pb(b,a,!0);if(d)throw new I(d);if(!b.Pa.rmdir)throw new I(63);if(c.ab)throw new I(10);b.Pa.rmdir(b,a);Lb(c)}
function Xb(a){var b=P(a,{parent:!0}).node;if(!b)throw new I(44);a=ab(a);var c=N(b,a),d=Pb(b,a,!1);if(d)throw new I(d);if(!b.Pa.unlink)throw new I(63);if(c.ab)throw new I(10);b.Pa.unlink(b,a);Lb(c)}function Hb(a){a=P(a).node;if(!a)throw new I(44);if(!a.Pa.readlink)throw new I(28);return db(Ib(a.parent),a.Pa.readlink(a))}function Yb(a,b){a="string"==typeof a?P(a,{ib:!0}).node:a;if(!a.Pa.Wa)throw new I(63);a.Pa.Wa(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Zb(a,b,c){if(""===a)throw new I(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=G(a);try{e=P(a,{ib:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new I(20);}else e=Tb(a,c,0),d=!0;if(!e)throw new I(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!K(e.mode))throw new I(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:K(e.mode)&&("r"!==Nb(b)||b&512)?31:Mb(e,Nb(b)):44))throw new I(c);if(b&512&&!d){c=e;c="string"==typeof c?P(c,{ib:!0}).node:c;if(!c.Pa.Wa)throw new I(63);if(K(c.mode))throw new I(31);if(32768!==(c.mode&61440))throw new I(28);if(d=Mb(c,"w"))throw new I(d);c.Pa.Wa(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Qb({node:e,path:Ib(e),flags:b,seekable:!0,position:0,Ra:e.Ra,Jb:[],error:!1});e.Ra.open&&e.Ra.open(e);!g.logReadFiles||b&1||($b||={},a in $b||($b[a]=1));return e}
function ac(a){if(null===a.fd)throw new I(8);a.lb&&(a.lb=null);try{a.Ra.close&&a.Ra.close(a)}catch(b){throw b;}finally{Cb[a.fd]=null}a.fd=null}function bc(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.Ra.bb)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.Ra.bb(a,b,c);a.Jb=[]}
function cc(a,b,c,d,e,f){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.Ra.write)throw new I(28);a.seekable&&a.flags&1024&&bc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new I(70);b=a.Ra.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function ha(a,b,c){dc=!0;g.stdin=a||g.stdin;g.stdout=b||g.stdout;g.stderr=c||g.stderr;g.stdin?T("/dev","stdin",g.stdin):Vb("/dev/tty","/dev/stdin");g.stdout?T("/dev","stdout",null,g.stdout):Vb("/dev/tty","/dev/stdout");g.stderr?T("/dev","stderr",null,g.stderr):Vb("/dev/tty1","/dev/stderr");Zb("/dev/stdin",0);Zb("/dev/stdout",1);Zb("/dev/stderr",1)}var dc;
function ec(a,b){a="string"==typeof a?a:Ib(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a+"/"+c);try{R(d)}catch(e){}a=d}}return d}function fc(a,b,c,d){a=G(("string"==typeof a?a:Ib(a))+"/"+b);c=zb(c,d);return Tb(a,(void 0!==c?c:438)&4095|32768,0)}
function xb(a,b,c,d,e,f){var h=b;a&&(a="string"==typeof a?a:Ib(a),h=b?G(a+"/"+b):a);a=zb(d,e);h=Tb(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Yb(h,a|146);b=Zb(h,577);cc(b,c,0,c.length,0,f);ac(b);Yb(h,a)}}
function T(a,b,c,d){a=G(("string"==typeof a?a:Ib(a))+"/"+b);b=zb(!!c,!!d);T.wb||(T.wb=64);var e=T.wb++<<8|0;mb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,h,k,n){for(var l=0,p=0;p<n;p++){try{var q=c()}catch(z){throw new I(29);}if(void 0===q&&0===l)throw new I(6);if(null===q||void 0===q)break;l++;h[k+p]=q}l&&(f.node.timestamp=Date.now());return l},write(f,h,k,n){for(var l=0;l<n;l++)try{d(h[k+l])}catch(p){throw new I(29);}n&&(f.node.timestamp=Date.now());return l}});return Ub(a,
b,e)}function gc(a){if(!(a.Gb||a.Hb||a.link||a.Qa)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.Qa=na(a.url),a.Sa=a.Qa.length}catch(b){throw new I(29);}}}
function hc(a,b,c,d,e){class f{constructor(){this.gb=!1;this.Ta=[];this.fb=void 0;this.pb=this.qb=0}get(p){if(!(p>this.length-1||0>p)){var q=p%this.chunkSize;return this.fb(p/this.chunkSize|0)[q]}}Ab(p){this.fb=p}rb(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),z,t=(z=p.getResponseHeader("Accept-Ranges"))&&"bytes"===z;p=(z=p.getResponseHeader("Content-Encoding"))&&
"gzip"===z;var r=1048576;t||(r=q);var u=this;u.Ab(F=>{var M=F*r,S=(F+1)*r-1;S=Math.min(S,q-1);if("undefined"==typeof u.Ta[F]){var Nc=u.Ta;if(M>S)throw Error("invalid range ("+M+", "+S+") or no bytes requested!");if(S>q-1)throw Error("only "+q+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);q!==r&&L.setRequestHeader("Range","bytes="+M+"-"+S);L.responseType="arraybuffer";L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);if(!(200<=
L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);M=void 0!==L.response?new Uint8Array(L.response||[]):jb(L.responseText||"");Nc[F]=M}if("undefined"==typeof u.Ta[F])throw Error("doXHR failed!");return u.Ta[F]});if(p||!q)r=q=1,r=q=this.fb(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.qb=q;this.pb=r;this.gb=!0}get length(){this.gb||this.rb();return this.qb}get chunkSize(){this.gb||this.rb();return this.pb}}
if("undefined"!=typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;var k=void 0}else k=c,h=void 0;var n=fc(a,b,d,e);h?n.Qa=h:k&&(n.Qa=null,n.url=k);Object.defineProperties(n,{Sa:{get:function(){return this.Qa.length}}});var l={};Object.keys(n.Ra).forEach(p=>{var q=n.Ra[p];l[p]=(...z)=>{gc(n);return q(...z)}});l.read=(p,q,z,t,r)=>{gc(n);p=p.node.Qa;if(r>=p.length)q=0;else{t=Math.min(p.length-
r,t);if(p.slice)for(var u=0;u<t;u++)q[z+u]=p[r+u];else for(u=0;u<t;u++)q[z+u]=p.get(r+u);q=t}return q};l.mb=()=>{gc(n);Ha();throw new I(48);};n.Ra=l;return n}var U={},$b;function ic(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Q(a).path;if(0==b.length)throw new I(44);return G(a+"/"+b)}var Ya=void 0,jc=0,mc=a=>{if(!(Qa||0<jc)){kc();Pa(za);dc=!1;lc(0);for(var b=0;b<Cb.length;b++){var c=Cb[b];c&&ac(c)}}Qa||0<jc||(g.onExit?.(a),ta=!0);la(a,new Oa(a))},nc=a=>{Qa=!1;jc=0;mc(a)};
g._emscripten_force_exit=nc;
var oc={},qc=()=>{if(!pc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ka||"./this.program"},b;for(b in oc)void 0===oc[b]?delete a[b]:a[b]=oc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);pc=c}return pc},pc,sc=a=>{var b=hb(a)+1,c=rc(b);ib(a,x,c,b);return c},tc=[],uc,V=a=>{var b=tc[a];b||(a>=tc.length&&(tc.length=a+1),tc[a]=b=uc.get(a));return b},vc=(a,
b,c,d)=>{var e={string:l=>{var p=0;null!==l&&void 0!==l&&0!==l&&(p=sc(l));return p},array:l=>{var p=rc(l.length);w.set(l,p);return p}};a=g["_"+a];var f=[],h=0;if(d)for(var k=0;k<d.length;k++){var n=e[c[k]];n?(0===h&&(h=W()),f[k]=n(d[k])):f[k]=d[k]}c=a(...f);return c=function(l){0!==h&&X(h);return"string"===b?l?H(x,l):"":"boolean"===b?!!l:l}(c)};[44].forEach(a=>{tb[a]=new I(a);tb[a].stack="<generic error, no stack>"});O=Array(4096);Sb(J,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");mb(259,{read:()=>0,write:(d,e,f,h)=>h});Ub("/dev/null",259);lb(1280,ob);lb(1536,pb);Ub("/dev/tty",1280);Ub("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=cb(a).byteLength);return a[--b]};T("/dev","random",c);T("/dev","urandom",c);R("/dev/shm");R("/dev/shm/tmp")})();
(function(){R("/proc");var a=R("/proc/self");R("/proc/self/fd");Sb({Xa(){var b=sb(a,"fd",16895,73);b.Pa={lookup(c,d){var e=Q(+d);c={parent:null,Xa:{xb:"fake"},Pa:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=ec;g.FS_createDataFile=xb;g.FS_createPreloadedFile=yb;g.FS_unlink=Xb;g.FS_createLazyFile=hc;g.FS_createDevice=T;
var kd={n:a=>{a=new Ua(a);0==w[a.Ua+12]&&(w[a.Ua+12]=1,Sa--);w[a.Ua+13]=0;Ra.push(a);wc(a.hb);if(xc(A[a.Ua+4>>2]))a=A[a.hb>>2];else{var b=A[a.Ua+16>>2];a=0!==b?b:a.hb}return a},q:()=>{Y(0,0);var a=Ra.pop();yc(a.hb);D=0},b:()=>Xa([]),f:a=>Xa([a]),m:(a,b)=>Xa([a,b]),F:()=>{var a=Ra.pop();a||Ha("no exception to throw");var b=a.hb;0==w[a.Ua+13]&&(Ra.push(a),w[a.Ua+13]=1,w[a.Ua+12]=0,Sa++);D=b;throw D;},s:(a,b,c)=>{Ta(new Ua(a),b,c);D=a;Sa++;throw D;},ma:()=>Sa,h:a=>{D||=a;throw D;},H:function(a,b,c){Ya=
c;try{var d=Q(a);switch(b){case 0:var e=E();if(0>e)break;for(;Cb[e];)e++;return Rb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=E(),d.flags|=e,0;case 12:return e=E(),ua[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.Va}},L:function(a,b){try{if(0===b)return-28;var c=hb("/")+1;if(b<c)return-68;ib("/",x,a,b);return c}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.Va}},la:function(a,
b,c){Ya=c;try{var d=Q(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.$a.Db){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=E();y[e>>2]=25856;y[e+4>>2]=5;y[e+8>>2]=191;y[e+12>>2]=35387;for(var f=0;32>f;f++)w[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.$a.Eb)for(e=E(),a=[],f=0;32>f;f++)a.push(w[e+f+17]);return 0;case 21519:if(!d.tty)return-59;
e=E();return y[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=E();if(!d.Ra.Cb)throw new I(59);return d.Ra.Cb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.$a.Fb&&(f=[24,80],e=E(),ua[e>>1]=f[0],ua[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof U||"ErrnoError"!==h.name)throw h;return-h.Va}},na:function(a,b,c,d){Ya=d;try{b=b?H(x,b):"";b=ic(a,b);var e=d?E():0;return Zb(b,c,e).fd}catch(f){if("undefined"==typeof U||
"ErrnoError"!==f.name)throw f;return-f.Va}},ca:function(a,b,c,d){try{b=b?H(x,b):"";d=d?H(x,d):"";b=ic(a,b);d=ic(c,d);a=b;var e=$a(a),f=$a(d),h=ab(a),k=ab(d);var n=P(a,{parent:!0});var l=n.node;n=P(d,{parent:!0});var p=n.node;if(!l||!p)throw new I(44);if(l.Xa!==p.Xa)throw new I(75);var q=N(l,h),z=eb(a,f);if("."!==z.charAt(0))throw new I(28);z=eb(d,e);if("."!==z.charAt(0))throw new I(55);try{var t=N(p,k)}catch(F){}if(q!==t){var r=K(q.mode),u=Pb(l,h,r);if(u)throw new I(u);if(u=t?Pb(p,k,r):Ob(p,k))throw new I(u);
if(!l.Pa.rename)throw new I(63);if(q.ab||t&&t.ab)throw new I(10);if(p!==l&&(u=Mb(l,"w")))throw new I(u);Lb(q);try{l.Pa.rename(q,p,k),q.parent=p}catch(F){throw F;}finally{Kb(q)}}return 0}catch(F){if("undefined"==typeof U||"ErrnoError"!==F.name)throw F;return-F.Va}},da:function(a){try{return a=a?H(x,a):"",Wb(a),0}catch(b){if("undefined"==typeof U||"ErrnoError"!==b.name)throw b;return-b.Va}},fa:function(a,b){try{a=a?H(x,a):"";var c=P(a,{ib:!0}).node;if(!c)throw new I(44);if(!c.Pa.Ya)throw new I(63);
var d=c.Pa.Ya(c);y[b>>2]=d.dev;y[b+4>>2]=d.mode;A[b+8>>2]=d.nlink;y[b+12>>2]=d.uid;y[b+16>>2]=d.gid;y[b+20>>2]=d.rdev;C=[d.size>>>0,(B=d.size,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[b+24>>2]=C[0];y[b+28>>2]=C[1];y[b+32>>2]=4096;y[b+36>>2]=d.blocks;var e=d.atime.getTime(),f=d.mtime.getTime(),h=d.ctime.getTime();C=[Math.floor(e/1E3)>>>0,(B=Math.floor(e/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>
0:0)];y[b+40>>2]=C[0];y[b+44>>2]=C[1];A[b+48>>2]=e%1E3*1E3;C=[Math.floor(f/1E3)>>>0,(B=Math.floor(f/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[b+56>>2]=C[0];y[b+60>>2]=C[1];A[b+64>>2]=f%1E3*1E3;C=[Math.floor(h/1E3)>>>0,(B=Math.floor(h/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[b+72>>2]=C[0];y[b+76>>2]=C[1];A[b+80>>2]=h%1E3*1E3;C=[d.ino>>>0,(B=d.ino,1<=+Math.abs(B)?0<B?+Math.floor(B/
4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[b+88>>2]=C[0];y[b+92>>2]=C[1];return 0}catch(k){if("undefined"==typeof U||"ErrnoError"!==k.name)throw k;return-k.Va}},ea:function(a,b,c){try{return b=b?H(x,b):"",b=ic(a,b),0===c?Xb(b):512===c?Wb(b):Ha("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.Va}},ba:()=>{Ha("")},oa:()=>1,U:(a,b,c)=>x.copyWithin(a,b,b+c),ga:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,
0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var k=h.getTimezoneOffset();A[a>>2]=60*Math.max(e,k);y[b>>2]=Number(e!=k);a=n=>n.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];f=a(f);h=a(h);k<e?(ib(f,x,c,17),ib(h,x,d,17)):(ib(f,x,d,17),ib(h,x,c,17))},aa:nc,K:()=>performance.now(),J:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%
65536)-sa.buffer.byteLength+65535)/65536;try{sa.grow(e);va();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},ha:(a,b)=>{var c=0;qc().forEach((d,e)=>{var f=b+c;e=A[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++]=d.charCodeAt(f);w[e]=0;c+=d.length+1});return 0},ia:(a,b)=>{var c=qc();A[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);A[b>>2]=d;return 0},_:mc,I:function(a){try{var b=Q(a);ac(b);return 0}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return c.Va}},ka:function(a,
b,c,d){try{a:{var e=Q(a);a=b;for(var f,h=b=0;h<c;h++){var k=A[a>>2],n=A[a+4>>2];a+=8;var l=e,p=f,q=w;if(0>n||0>p)throw new I(28);if(null===l.fd)throw new I(8);if(1===(l.flags&2097155))throw new I(8);if(K(l.node.mode))throw new I(31);if(!l.Ra.read)throw new I(28);var z="undefined"!=typeof p;if(!z)p=l.position;else if(!l.seekable)throw new I(70);var t=l.Ra.read(l,q,k,n,p);z||(l.position+=t);var r=t;if(0>r){var u=-1;break a}b+=r;if(r<n)break;"undefined"!=typeof f&&(f+=r)}u=b}A[d>>2]=u;return 0}catch(F){if("undefined"==
typeof U||"ErrnoError"!==F.name)throw F;return F.Va}},X:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Q(a);bc(f,b,d);C=[f.position>>>0,(B=f.position,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[e>>2]=C[0];y[e+4>>2]=C[1];f.lb&&0===b&&0===d&&(f.lb=null);return 0}catch(h){if("undefined"==typeof U||"ErrnoError"!==h.name)throw h;return h.Va}},ja:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var f,
h=b=0;h<c;h++){var k=A[a>>2],n=A[a+4>>2];a+=8;var l=cc(e,w,k,n,f);if(0>l){var p=-1;break a}b+=l;"undefined"!=typeof f&&(f+=l)}p=b}A[d>>2]=p;return 0}catch(q){if("undefined"==typeof U||"ErrnoError"!==q.name)throw q;return q.Va}},$:zc,Y:Ac,G:Bc,e:Cc,w:Dc,c:Ec,d:Fc,t:Gc,Z:Hc,r:Ic,p:Jc,x:Kc,z:Lc,E:Mc,D:Oc,N:Pc,O:Qc,P:Rc,W:Sc,Q:Tc,V:Uc,R:Vc,M:Wc,i:Xc,l:Yc,g:Zc,j:$c,k:ad,o:bd,y:cd,v:dd,B:ed,C:fd,A:gd,T:hd,S:jd,u:a=>a,a:sa},Z=function(){function a(c){Z=c.exports;uc=Z.sa;xa.unshift(Z.pa);Ga("wasm-instantiate");
return Z}var b={a:kd};Fa("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){m(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ja||=Ia("rapfi-single.wasm")?"rapfi-single.wasm":g.locateFile?g.locateFile("rapfi-single.wasm",v):v+"rapfi-single.wasm";Na(b,function(c){a(c.instance)}).catch(ba);return{}}();g._gomocupLoopOnce=()=>(g._gomocupLoopOnce=Z.qa)();
var ld=g._main=(a,b)=>(ld=g._main=Z.ra)(a,b),kc=()=>(kc=Z.ta)(),lc=a=>(lc=Z.ua)(a),Y=(a,b)=>(Y=Z.va)(a,b),Va=a=>(Va=Z.wa)(a),X=a=>(X=Z.xa)(a),rc=a=>(rc=Z.ya)(a),W=()=>(W=Z.za)(),yc=a=>(yc=Z.Aa)(a),wc=a=>(wc=Z.Ba)(a),Wa=(a,b,c)=>(Wa=Z.Ca)(a,b,c),xc=a=>(xc=Z.Da)(a),md=g.dynCall_iij=(a,b,c,d)=>(md=g.dynCall_iij=Z.Ea)(a,b,c,d),nd=g.dynCall_ji=(a,b)=>(nd=g.dynCall_ji=Z.Fa)(a,b),od=g.dynCall_j=a=>(od=g.dynCall_j=Z.Ga)(a),pd=g.dynCall_iiiiij=(a,b,c,d,e,f,h)=>(pd=g.dynCall_iiiiij=Z.Ha)(a,b,c,d,e,f,h),qd=
g.dynCall_viiij=(a,b,c,d,e,f)=>(qd=g.dynCall_viiij=Z.Ia)(a,b,c,d,e,f),rd=g.dynCall_viiji=(a,b,c,d,e,f)=>(rd=g.dynCall_viiji=Z.Ja)(a,b,c,d,e,f),sd=g.dynCall_vij=(a,b,c,d)=>(sd=g.dynCall_vij=Z.Ka)(a,b,c,d),td=g.dynCall_jii=(a,b,c)=>(td=g.dynCall_jii=Z.La)(a,b,c),ud=g.dynCall_jiii=(a,b,c,d)=>(ud=g.dynCall_jiii=Z.Ma)(a,b,c,d),vd=g.dynCall_iiij=(a,b,c,d,e)=>(vd=g.dynCall_iiij=Z.Na)(a,b,c,d,e),wd=g.dynCall_iiiij=(a,b,c,d,e,f)=>(wd=g.dynCall_iiiij=Z.Oa)(a,b,c,d,e,f);
function Ec(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Fc(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function $c(a,b,c,d){var e=W();try{V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function Zc(a,b,c){var d=W();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Xc(a){var b=W();try{V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}
function Cc(a,b){var c=W();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Lc(a,b,c,d,e,f,h){var k=W();try{return V(a)(b,c,d,e,f,h)}catch(n){X(k);if(n!==n+0)throw n;Y(1,0)}}function Yc(a,b){var c=W();try{V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function ad(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(h){X(f);if(h!==h+0)throw h;Y(1,0)}}function Bc(a){var b=W();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}
function Kc(a,b,c,d,e,f){var h=W();try{return V(a)(b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function Gc(a,b,c,d,e){var f=W();try{return V(a)(b,c,d,e)}catch(h){X(f);if(h!==h+0)throw h;Y(1,0)}}function bd(a,b,c,d,e,f){var h=W();try{V(a)(b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function Dc(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Ic(a,b,c,d,e,f){var h=W();try{return V(a)(b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}
function cd(a,b,c,d,e,f,h){var k=W();try{V(a)(b,c,d,e,f,h)}catch(n){X(k);if(n!==n+0)throw n;Y(1,0)}}function Jc(a,b,c,d,e,f,h){var k=W();try{return V(a)(b,c,d,e,f,h)}catch(n){X(k);if(n!==n+0)throw n;Y(1,0)}}function dd(a,b,c,d,e,f,h,k){var n=W();try{V(a)(b,c,d,e,f,h,k)}catch(l){X(n);if(l!==l+0)throw l;Y(1,0)}}function zc(a,b){var c=W();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}
function Hc(a,b,c,d,e,f){var h=W();try{return V(a)(b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function Mc(a,b,c,d,e,f,h,k){var n=W();try{return V(a)(b,c,d,e,f,h,k)}catch(l){X(n);if(l!==l+0)throw l;Y(1,0)}}function Oc(a,b,c,d,e,f,h,k,n,l,p,q){var z=W();try{return V(a)(b,c,d,e,f,h,k,n,l,p,q)}catch(t){X(z);if(t!==t+0)throw t;Y(1,0)}}function ed(a,b,c,d,e,f,h,k,n,l,p){var q=W();try{V(a)(b,c,d,e,f,h,k,n,l,p)}catch(z){X(q);if(z!==z+0)throw z;Y(1,0)}}
function fd(a,b,c,d,e,f,h,k,n,l,p,q,z,t,r,u){var F=W();try{V(a)(b,c,d,e,f,h,k,n,l,p,q,z,t,r,u)}catch(M){X(F);if(M!==M+0)throw M;Y(1,0)}}function Ac(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Sc(a,b,c,d){var e=W();try{return md(a,b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function Uc(a,b){var c=W();try{return nd(a,b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}
function gd(a,b,c,d,e,f){var h=W();try{qd(a,b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function hd(a,b,c,d,e,f){var h=W();try{rd(a,b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function jd(a,b,c,d){var e=W();try{sd(a,b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function Vc(a,b,c){var d=W();try{return td(a,b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Tc(a){var b=W();try{return od(a)}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}
function Rc(a,b,c,d,e){var f=W();try{return vd(a,b,c,d,e)}catch(h){X(f);if(h!==h+0)throw h;Y(1,0)}}function Qc(a,b,c,d,e,f){var h=W();try{return wd(a,b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function Pc(a,b,c,d,e,f,h){var k=W();try{return pd(a,b,c,d,e,f,h)}catch(n){X(k);if(n!==n+0)throw n;Y(1,0)}}function Wc(a,b,c,d){var e=W();try{return ud(a,b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}g.addRunDependency=Fa;g.removeRunDependency=Ga;
g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>vc(a,b,c,f)};g.FS_createPreloadedFile=yb;g.FS_unlink=a=>Xb(a);g.FS_createPath=ec;g.FS_createDevice=T;g.FS_createDataFile=(a,b,c,d,e,f)=>{xb(a,b,c,d,e,f)};g.FS_createLazyFile=hc;var xd;Ea=function yd(){xd||zd();xd||(Ea=yd)};
function Ad(a=[]){var b=ld;a.unshift(ka);var c=a.length,d=rc(4*(c+1)),e=d;a.forEach(h=>{A[e>>2]=sc(h);e+=4});A[e>>2]=0;try{var f=b(c,d);mc(f,!0)}catch(h){h instanceof Oa||"unwind"==h||la(1,h)}}
function zd(){var a=ja;function b(){if(!xd&&(xd=!0,g.calledRun=!0,!ta)){g.noFSInit||dc||ha();Eb=!1;Pa(xa);Pa(ya);aa(g);g.onRuntimeInitialized?.();Bd&&Ad(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Aa.unshift(c)}Pa(Aa)}}if(!(0<Ca)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ba();Pa(wa);0<Ca||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},
1);b()},1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Bd=!0;g.noInitialRun&&(Bd=!1);zd();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Rapfi;
else if (typeof define === 'function' && define['amd'])
  define([], () => Rapfi);
